---
permalink: audit/accessing-audit-log-file.html
sidebar: sidebar
keywords: storagegrid, audit, log, log file, access, accessing
summary: 'The audit share contains the active audit.log file and any compressed audit log files. You can access audit log files directly from the command line of the Admin Node.'
---
= Access audit log file
:icons: font
:imagesdir: ../media/

[.lead]
The audit share contains the active `audit.log` file and any compressed audit log files. You can access audit log files directly from the command line of the Admin Node.

The `audit.log` file remains empty unless you configure StorageGRID for *Admin Nodes/local nodes* or *Admin Node and external syslog server*. For more information, refer to link:../monitor/configure-audit-messages.html#select-audit-information-destinations[Select audit information destinations].

.Before you begin

* You have link:../admin/admin-group-permissions.html[specific access permissions].
* You must have the `Passwords.txt` file.
* You must know the IP address of an Admin Node.

.Steps

. Log in to an Admin Node:
.. Enter the following command: `ssh admin@_primary_Admin_Node_IP_`
.. Enter the password listed in the `Passwords.txt` file.
.. Enter the following command to switch to root: `su -`
.. Enter the password listed in the `Passwords.txt` file.
+
When you are logged in as root, the prompt changes from `$` to `#`.

. Go to the directory containing the audit log files:
+
`cd  /var/local/audit/export/`
. View the current or a saved audit log file, as required.

// 2025 AUG 6, SGRIDDOC-172