---
permalink: swnodes/installing-storagegrid-webscale-host-services.html
sidebar: sidebar
keywords: how to install StorageGRID host services
summary: 'You use the StorageGRID package for your operating system type to install the StorageGRID host services.'
---
= Install StorageGRID host services (RHEL, Ubuntu, or Debian)
:icons: font
:imagesdir: ../media/

[.lead]
You use the StorageGRID package for your operating system type to install the StorageGRID host services.

[role="tabbed-block"]
====

.RHEL
--
You use the StorageGRID RPM package to install the StorageGRID host services.

.About this task

These instructions describe how to install the host services from the RPM packages. As an alternative, you can use the DNF repository metadata included in the installation archive to install the RPM packages remotely. See the DNF repository instructions for your Linux operating system.

.Steps

. Copy the StorageGRID RPM packages to each of your hosts, or make them available on shared storage.
+
For example, place them in the `/tmp` directory, so you can use the example command in the next step.

. Log in to each host as root or using an account with sudo permission, and run the following commands in the order specified:
+
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Images-version-SHA.rpm
----
+
----
sudo dnf --nogpgcheck localinstall /tmp/StorageGRID-Webscale-Service-version-SHA.rpm
----
+
CAUTION: You must install the Images package first, and the Service package second.
+
NOTE: If you placed the packages in a directory other than `/tmp`, modify the command to reflect the path you used.
--

.Ubuntu or Debian
--
You use the StorageGRID DEB package to install the StorageGRID host services for Ubuntu, or Debian.

.About this task

These instructions describe how to install the host services from the DEB packages. As an alternative, you can use the APT repository metadata included in the installation archive to install the DEB packages remotely. See the APT repository instructions for your Linux operating system.

.Steps

. Copy the StorageGRID DEB packages to each of your hosts, or make them available on shared storage.
+
For example, place them in the `/tmp` directory, so you can use the example command in the next step.

. Log in to each host as root or using an account with sudo permission, and run the following commands.
+
You must install the `images` package first, and the `service` package second. If you placed the packages in a directory other than `/tmp`, modify the command to reflect the path you used.
+
----
sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb
----
+
----
sudo dpkg --install /tmp/storagegrid-webscale-service-version-SHA.deb
----
+
NOTE: Python 2.7 must already be installed before the StorageGRID packages can be installed. The `sudo dpkg --install /tmp/storagegrid-webscale-images-version-SHA.deb` command will fail until you have done so.

--
====

