---
permalink: upgrade/changes-to-grid-management-api.html
sidebar: sidebar
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 11.8 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported.'
---
= Changes to the Grid Management API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 11.9 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported. 

NOTE: You can continue to use deprecated versions of the management API with StorageGRID 11.9; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 11.9, the deprecated APIs can be deactivated using the `PUT /grid/config/management` API.

To learn more, go to link:../admin/using-grid-management-api.html[Use the Grid Management API].

== Legacy mgmt-api requests removed

These legacy requests have been removed:

`/grid/server-types`

`/grid/ntp-roles`

== Changes to `GET /private/storage-usage` API
* A new property, `usageCacheDuration`, has been added to the response body. This property specifies the duration (in seconds) for which the usage lookup cache remains valid. This value applies when checking the usage against tenant storage quota and bucket capacity limits.
* The `GET /api/v4//private/storage-usage` behavior has been corrected to match nesting from the schema.
* These changes apply only to the private API.
// 2024-07-2, jira SWGS-31283