---
permalink: upgrade/changes-to-grid-management-api.html
sidebar: sidebar
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.0 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported.'
---
= Changes to the Grid Management API
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 12.0 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported. 

NOTE: You can continue to use deprecated versions of the management API with StorageGRID 12.0; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 12.0, you can deactivate the deprecated APIs by using the `PUT /grid/config/management` API.

To learn more, go to link:../admin/using-grid-management-api.html[Use the Grid Management API].

== New private endpoints for Move ADC
The following private endpoints have been added to allow you to link:../maintain/move-adc-service.html[move the ADC service] from one Storage Node to another on the same site:

`/private/move-adc`

`/private/move-adc/start`

`/private/move-adc/retry`

== New private endpoints for Convert to data-only node
The following private endpoints have been added to allow you to link:../maintain/convert-to-data-only-node.html[convert one or more combined Storage Nodes] that don't contain the ADC service into data-only nodes.

`/private/convert-to-data-only-node`

`/private/convert-to-data-only-node/start`

`/private/convert-to-data-only-node/retry`


// 2024-07-2, jira SWGS-31283
// 2024-07-11, SGWS-32010
// 2025-02-24, SWGS-34787