---
permalink: upgrade/how-your-system-is-affected-during-upgrade.html
sidebar: sidebar
keywords: upgrade, firmware, appliance, alert
summary: 'Learn how your StorageGRID system will be affected during upgrade.'
---
= How your system is affected during the upgrade
:icons: font
:imagesdir: ../media/

[.lead]
Learn how your StorageGRID system will be affected during upgrade.

== External SSH access is allowed until upgrade completes

External SSH access is allowed during the upgrade. When the upgrade completes, external SSH access is blocked by default. After upgrading, you can use the *Block SSH* tab available on the *Grid Manager* > *Security Settings* page to link:../admin/manage-ssh-access.html[manage external SSH access]. SSH access between grid nodes isn't affected.

== StorageGRID upgrades are non-disruptive

The StorageGRID system can ingest and retrieve data from client applications throughout the upgrade process. If you approve all nodes of the same type to upgrade (for example, Storage Nodes), the nodes are brought down one at a time, so there is no time when all grid nodes or all grid nodes of a certain type are unavailable.

To allow for continued availability, ensure that your ILM policy contains rules that specify storing multiple copies of each object. You must also ensure that all external S3 clients are configured to send requests to one of the following:

* A high availability (HA) group virtual IP address
* A high availability third-party load balancer
* Multiple Gateway Nodes for each client
* Multiple Storage Nodes for each client

== Client applications might experience short-term disruptions

The StorageGRID system can ingest and retrieve data from client applications throughout the upgrade process; however, client connections to individual Gateway Nodes or Storage Nodes might be disrupted temporarily if the upgrade needs to restart services on those nodes. Connectivity will be restored after the upgrade process completes and services resume on the individual nodes.

You might need to schedule downtime to apply an upgrade if loss of connectivity for a short period is not acceptable. You can use selective approval to schedule when certain nodes are updated.

NOTE: You can use multiple gateways and high availability (HA) groups to provide automatic failover during the upgrade process. See the instructions for link:../admin/configure-high-availability-group.html[configuring high availability groups].

== Background repairs paused on grids with mixed-version nodes

Background repairs don't run during upgrade when the grid contains mixed-version nodes. Any inconsistencies that occur during a site outage won't be repaired until the upgrade is complete.

== Appliance firmware is upgraded

During the StorageGRID 12.0 upgrade:

* All StorageGRID appliance nodes are automatically upgraded to StorageGRID Appliance Installer firmware version 12.0.
*	SG6060 and SGF6024 appliances are automatically upgraded to BIOS firmware version 3B08.EX and BMC firmware version 4.01.07.
*	SG100 and SG1000 appliances are automatically upgraded to BIOS firmware version 3B13.EC and BMC firmware version 4.75.07.
*	SGF6112, SG6160, SG110 and SG1100 appliances are automatically upgraded to BIOS firmware version 3A14.QD and BMC firmware version 3.19.07.

== ILM policies are handled differently according to their status

*	The active policy will remain the same after upgrade.
* Only the latest 10 historical policies are preserved on upgrade.
* If there is a proposed policy, it will be deleted during upgrade.

== Alerts might be triggered

Alerts might be triggered when services start and stop and when the StorageGRID system is operating as a mixed-version environment (some grid nodes running an earlier version, while others have been upgraded to a later version). Other alerts might be triggered after the upgrade completes. 

For example, you might see the *Unable to communicate with node* alert when services are stopped, or you might see the *Cassandra communication error* alert when some nodes have been upgraded to StorageGRID 12.0 but other nodes are still running StorageGRID 11.9. In general, these alerts will clear when the upgrade completes.

The *ILM placement unachievable* alert might be triggered when Storage Nodes are stopped during the upgrade to StorageGRID 12.0. This alert might persist for 1 day after the upgrade completes.

After the upgrade completes, you can review any upgrade-related alerts by selecting *Recently resolved alerts* or *Current alerts* from the Grid Manager dashboard.

== Configuration changes are restricted

NOTE: This list applies specifically to upgrades from StorageGRID 11.9 to StorageGRID 12.0. If you're upgrading to another StorageGRID release, refer to the list of restricted changes in the upgrade instructions for that release.

Until the *Enable New Feature* task completes:

* Don't make any grid configuration changes.
* Don't enable or disable any new features. 
* Don't update the ILM configuration. Otherwise, you might experience inconsistent and unexpected ILM behavior.
* Don't apply a hotfix or recover a grid node.
+
NOTE: Contact technical support if you need to recover a node during upgrade.

* You should not manage HA groups, VLAN interfaces, or load balancer endpoints while you're upgrading to StorageGRID 12.0.

* Don't delete any HA groups until the upgrade to StorageGRID 12.0 is complete. Virtual IP addresses in other HA groups might become inaccessible.

Until the *Final Upgrade Steps* task completes:

* Don't perform an expansion procedure.
* Don't perform a decommission procedure.

// 2025 APR 16, SGWS-34284