---
permalink: upgrade/removed-or-deprecated-features.html
sidebar: sidebar
keywords:
summary: 'Some features and capabilities were removed or deprecated in this release. Review these items to understand whether you need to update client applications or modify your configuration before you upgrade.'
---
= Removed or deprecated features and capabilities
:icons: font
:imagesdir: ../media/

[.lead]
Some features and capabilities were removed or deprecated in this release. Review these items to understand whether you need to update client applications or modify your configuration before you upgrade.

== Definitions

Deprecated:: The feature *should not* be used in new production environments. Existing production environments can continue using the feature.
End of Life:: Last shipped version that contains the feature. No future versions will support the feature. In some cases, documentation for the feature might be removed at this stage.
Removed:: First version that *does not* contain the feature.

== StorageGRID end of feature support

Deprecated features will be removed in N+2 major versions. For example, if a feature is deprecated in version N (for example, 6.3), the last version where the feature will exist is N+1 (for example, 6.4). Version N+2 (for example, 6.5) is the first release when the feature doesn't exist in the product.

See the https://mysupport.netapp.com/site/info/version-support[Software Version Support page^] for additional information.

NOTE: In certain situations, NetApp might end support for particular features sooner than indicated.

[cols="2a,1a,1a,1a,3a" options="header"]
|===
| Feature| Deprecated| End of Life| Removed| Links to earlier documentation

| Alarms (_not Alerts_)
| 11.7
| 11.8
| 11.9
| https://docs.netapp.com/us-en/storagegrid-118/monitor/alarms-reference.html[Alarms reference (StorageGRID 11.8)^]

| Archive Node support
| 11.7
| 11.8
| 11.9
| https://docs.netapp.com/us-en/storagegrid-118/maintain/considerations-for-decommissioning-admin-or-gateway-nodes.html[Considerations for decommissioning Archive Nodes (StorageGRID 11.8)^]

*Note*: You must decommission all Archive Nodes before you can upgrade to StorageGRID 11.9.

| Audit export through CIFS/Samba
| 11.1
| 11.6
| 11.7
| 

| CLB service
| 11.4
| 11.6
| 11.7
| 

| Docker container engine
| 11.8
| 11.9
| 12.0
| Support for Docker as the container engine for software-only deployments is deprecated. Docker will be replaced with another container engine in a future release. Refer to this link:../ubuntu/software-requirements.html#docker-versions-tested[example of current support].

| NFS audit export
| 11.8
| 11.9
| 12.0
| 

| Swift API support
| 11.7
| 11.9
| 12.0
| https://docs.netapp.com/us-en/storagegrid-118/swift/index.html[Use Swift REST API (StorageGRID 11.8)^]
|===