---
permalink: upgrade/verifying-installed-version-of-storagegrid.html
sidebar: sidebar
keywords: storagegrid, version, current version, previous version
summary: 'Before starting the upgrade, verify that the previous version of StorageGRID is currently installed with the latest available hotfix applied.'
---
= Verify the installed version of StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
Before starting the upgrade, verify that the previous version of StorageGRID is currently installed with the latest available hotfix applied.

.About this task

Before you upgrade to StorageGRID 12.0, your grid must have StorageGRID 11.9.0.8 or higher installed. If you are currently using a previous version of StorageGRID, you must install all previous upgrade files along with their latest hotfixes (strongly recommended) until your grid's current version is at least StorageGRID 11.9.0.8.

One possible upgrade path is shown in the <<example-upgrade-path,example>>.

CAUTION: NetApp strongly recommends that you apply the latest hotfix for each StorageGRID version before upgrading to the next version and that you also apply the latest hotfix for each new version you install. In some cases, you must apply a hotfix to avoid the risk of data loss. Refer to https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^] and the release notes for each hotfix to learn more. 

== Verify installed version

.Steps

. Sign in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].

. From the top of the Grid Manager, select *Help* > *About*.

. Verify that *Version* is 11.9.0.8 or higher.
//+
//In the StorageGRID 11.9._x.y_ version number:
//+
//** The *major release* has an _x_ value of 0 (11.9.0).
// ** A *hotfix*, if one has been applied, has a _y_ value (for example, 11.9.0.1).

. If *Version* isn't  or higher, go to https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads: StorageGRID^] to download the files for each previous release, including the latest hotfix for each release.

. Obtain the the upgrade instructions for each release you downloaded. Then, perform the software upgrade procedure for that release, and apply the latest hotfix for that release (strongly recommended).
+
Refer to the link:../maintain/storagegrid-hotfix-procedure.html[StorageGRID hotfix procedure].

== [[example-upgrade-path]]Example: Upgrade to StorageGRID 12.0 from version 11.8

The following example shows the steps to upgrade from StorageGRID version 11.8 to version 11.9 in preparation for a StorageGRID 12.0 upgrade. 

Download and install software in the following sequence to prepare your system for upgrade:

. Upgrade to the StorageGRID 11.8.0 major release.
. Apply the latest StorageGRID 11.8.0._y_ hotfix.
. Upgrade to the StorageGRID 11.9.0 major release.
. Apply the latest StorageGRID 11.9.0.8 hotfix.