---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 12.0
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 12.0
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== S3 consistency

=== Quorum consistency for new 12.0 installations
Fresh installations of StorageGRID 12.0 and later will default to using Quorum semantics when link:../s3/consistency.html[strong-global consistency] is set. The new behavior for strong-global consistency provides site failure tolerance for client requests when grids have three or more sites. The performance characteristics of Quorum semantics will differ depending on client application workload. If you need to revert to the previous behavior for strong-global consistency, follow <link> for instructions.

If you upgrade from StorageGRID 11.9 to StorageGRID 12.0, upgraded grids will keep the previous behavior for strong-global consistency. If you want to enable Quorum semantics, follow <link> for instructions.

