---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 12.0
summary: 'This release of StorageGRID introduces the following features and functional changes.'
---
= What's new in StorageGRID 12.0
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== Security

=== Security enhancement for encrypted passwords on disk

Improved password security, including a highly increased hash round count for SHA512 password hashes.

== S3 consistency

=== Quorum consistency for new 12.0 installations
Fresh installations of StorageGRID 12.0 and later will default to using Quorum semantics when strong-global consistency is set. The new behavior for strong-global consistency tolerates a single site failure for grids with three sites or more, but all client reads will incur cross-site latency. If you need to revert to the previous behavior for strong-global consistency, follow <link> for instructions.

If you upgrade from StorageGRID 11.9 to StorageGRID 12.0, upgraded grids will keep the existing behavior for strong-global consistency.