---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.9
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.9
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== Install, upgrade, hotfix

=== Default audit destinations
Fresh installations of StorageGRID 11.9 default to local node audit destinations. For information about changing audit log destinations, refer to link:../monitor/configure-audit-messages.html#Select-audit-information-destinations[Select audit information destinations]. (see email from KenW/Aron re: Query re tech case #2009937024, 16 feb 2024)

== Appliances

.


== Configure and manage

=== 5,000 buckets per tenant
StorageGRID now supports up to link:../s3/operations-on-buckets.html[5,000 S3 buckets per tenant].

== Expand grid, maintain grid, recover or replace nodes

Archive Nodes:: Support for Archive Nodes has been removed.
+
[NOTE]
====
Before starting your upgrade, you must:

. Decommission all Archive Nodes. See https://docs.netapp.com/us-en/storagegrid-118/maintain/grid-node-decommissioning.html[Grid node decommissioning (StorageGRID 11.8 doc site)^].
. Remove all Archive Node references from the Cloud Storage Pools and ILM policies. See https://kb.netapp.com/hybrid/StorageGRID/Maintenance/StorageGRID_11.9_software_upgrade_resolution_guide[NetApp Knowledge Base: StorageGRID 11.9 software upgrade resolution guide^].
====

== Grid Manager

=== Erasure-coding profiles page moved
The Erasure-coding profiles page is now at *CONFIGURATION* > *System* > *Erasure coding*. It used to be in the ILM menu.

=== Search enhancements
The link:../primer/exploring-grid-manager.html#search-field[search function] has been enhanced to provide more targeted results.

== Tenant Manager

=== Support for IAM Roles Anywhere
Added support for link:../ilm/creating-cloud-storage-pool.html[IAM Roles Anywhere authentication] for Cloud Storage Pools.

== S3 REST API

== Storage Node types
StorageGRID 11.8 provided the ability to install software-based, metadata-only Storage Nodes. StorageGRID 11.9 enables you to install software-based or appliance-based metadata-only _and_ data-only Storage Nodes. See link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes].