---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 12.0
summary: 'This release of StorageGRID introduces the following features and functional changes.'
---
= What's new in StorageGRID 12.0
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== Cross-grid replication with S3 Object Lock
You can configure cross-grid replication between buckets with S3 Object Lock enabled. Refer to link:../admin/grid-federation-what-is-cross-grid-replication.html#cgr-with-ol[How objects with retention settings are replicated].

NetApp recommends using this feature only between StorageGRID 12.0 source and destination buckets. However, this feature is supported between StorageGRID 11.9 buckets with S3 Object Lock disabled and StorageGRID 12.0 buckets with S3 Object Lock enabled.

== Security

=== Security enhancement for encrypted passwords on disk
Improved password security, including a highly increased hash round count for SHA512 password hashes.

== S3 consistency

=== Quorum consistency for new 12.0 installations
Fresh installations of StorageGRID 12.0 and later will default to using Quorum semantics when link:../s3/consistency.html[strong-global consistency] is set. The new behavior for strong-global consistency tolerates a single site failure for grids with three sites or more. The performance characteristics of Quorum semantics will differ depending on client application workload. If you need to revert to the previous behavior for strong-global consistency, follow <link> for instructions.

If you upgrade from StorageGRID 11.9 to StorageGRID 12.0, upgraded grids will keep the previous behavior for strong-global consistency. If you want to enable Quorum semantics, follow <link> for instructions.

== User interface

=== Dark theme
Dark theme and system theme settings are available in the User menu of the Grid Manager and Tenant Manager.
