---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 11.9
summary: 'This release of StorageGRID introduces the following features.'
---
= What's new in StorageGRID 11.9
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== Scalability

== Cloud Storage Pool enhancements
=== Support for IAM Roles Anywhere
Added support for link:../ilm/creating-cloud-storage-pool.html[IAM Roles Anywhere authentication] for Cloud Storage Pools.

== Multi-tenancy
=== 5,000 buckets per tenant
StorageGRID now supports up to link:../s3/operations-on-buckets.html[5,000 S3 buckets per tenant].

== S3 Object Lock improvements

== S3 compatibility

== Maintenance and Supportability

== Security

== Appliances (ask Kevin)

== Install, upgrade, hotfix

== Performance
=== Default audit destinations
Fresh installations of StorageGRID 11.9 default to local node audit destinations. Previously, audit messages were sent to the audit log (`/var/local/log/audit.log`) on Admin Nodes only.

For information about changing audit log destinations, refer to link:../monitor/configure-audit-messages.html#Select-audit-information-destinations[Select audit information destinations]. (see email from KenW/Aron re: Query re tech case #2009937024, 16 feb 2024)

== Grid Manager enhancements

=== Erasure-coding profiles page moved
The Erasure-coding profiles page is now at *CONFIGURATION* > *System* > *Erasure coding*. It used to be in the ILM menu.

=== Search enhancements
The link:../primer/exploring-grid-manager.html#search-field[search function] has been enhanced to provide more targeted results.

== Storage Node types
StorageGRID 11.8 provided the ability to install software-based, metadata-only Storage Nodes. StorageGRID 11.9 enables you to install software-based or appliance-based metadata-only _and_ data-only Storage Nodes. See link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes].