---
permalink: upgrade/whats-new.html
sidebar: sidebar
keywords: what is new in StorageGRID 12.0
summary: 'This release of StorageGRID introduces the following features and functional changes.'
---
= What's new in StorageGRID 12.0
:icons: font
:imagesdir: ../media/

[.lead]
This release of StorageGRID introduces the following features and functional changes.

== Appliances 
* Significantly increased storage capacity and cost efficiency with 122 TB QLC drives. 

* Automated drive firmware upgrades enhance system reliability and reduce maintenance overhead. 

* Allows conversion of existing Storage Nodes into data-only Storage Nodes to optimize resources and improve system flexibility.

== Artificial intelligence (AI) and machine learning (ML)
* link:../tenant/manage-branch-bucket-html[Branch buckets] allow point-in-time versions of buckets that facilitate faster ransomware recovery and isolated datasets for testing and experimentation. 

* An S3 caching layer enhances performance for AI/ML training.

== Capacity
StorageGRID now supports one trillion objects, which is three times the previous limit. 

== Cassandra updates
StorageGRID now uses a newer version of Cassandra for metadata storage. This version of Cassandra uses disk space more efficiently.

After you link:../upgrade/index.html[upgrade from StorageGRID 11.9 to 12.0], a metadata format update will occur in the background for one to three days. During this time, certain maintenance procedures, such as expansion, will be disabled.

== Federation 
* You can now link:../admin/managing-users.html#import-federated-users[import up to 100 federated users] into StorageGRID.

* You can now link:../ilm/configuring-regions-optional-and-s3-only.html[modify the default region] for S3 buckets. This capability provides greater flexibility in managing data locale and compliance. 

* link:grid-federation-what-is-cross-grid-replication.html[Cross-grid replication] has been enhanced to achieve feature parity between internal and external replication, enabling better scalability and the concept of grid federation for exabyte-scale storage.

* *QUESTION: No endpoints listed in changes-to-grid-management-api?* New API endpoints for replicating individual objects to enable precise control over data replication.

== Manageability 
* Faster link:../maintain/decommission-procedure.html[decommissioning] reduces time and complexity to improve operational efficiency. 

* Improved behavior for strong-global consistency provides site failure tolerance for client requests when grids have three or more sites. 
** Fresh installations of StorageGRID 12.0 and later will default to using Quorum semantics when link:../s3/consistency.html[strong-global consistency] is set.
** If you upgrade from StorageGRID 11.9 to StorageGRID 12.0, upgraded grids will keep the previous behavior for strong-global consistency.

NOTE: If you need to revert to the previous behavior for strong-global consistency, follow https://kb.netapp.com/hybrid/StorageGRID/Object_Mgmt/Configuring_StorageGRID_quorum_semantics_for_strong-global_consistency[Configure StorageGRID Quorum semantics for strong-global consistency^] for instructions.

* Notifications through Webhooks to support additional receivers (FluentIO): A new link:../admin/manage-platform-services-for-tenants.html[webhook integration for bucket event notifications] will support more developer workflows, enabling automated downstream processes. 

* link:../admin/configure-autosupport-grid-manager.html[User-triggered AutoSupport] empowers users to initiate support uploads to enhance support responsiveness. 

* Reduced https://docs.netapp.com/us-en/storagegrid-appliances/index.html[appliance^] reboot time minimizes downtime to improve overall system availability. 

* link:../maintain/move-adc-service.html[The ability to move the ADC service] to another node increases flexibility and resilience in managing administrative nodes. 

* The ability for any Admin Node to link:../maintain/selecting-node-recovery-procedure.html[recover any other node] (except the primary Admin Node) enhances system recovery and fault tolerance, improving overall reliability.

* Users can now use an S3 bucket to link:../monitor/configure-audit-messages.html#use-a-bucket[store audit logs for a long period of time].

* You can link:../maintain/move-adc-service.html[move the ADC service] before you decommission a Storage Node or convert a Storage Node to a data-only node.

== S3 API 
* *QUESTION: What's new for 12.0? Condition keys have been around since at least 11.2* Support for condition keys: Allows more granular access policies to improve security and compliance. 

* *QUESTION: New for 12.0?* The x-amz-side-encryption-customer-algorithm supports customer-specified encryption algorithms for enhanced data security. 

* *QUESTION: New for 12.0?* S3:object-lock-mode provides data protection by enforcing write-once-read-many (WORM) policies. 

== Tenant groups
* You can now configure a new S3 trust policy to support the link:../tenant/manage-groups.html#set-up-assumerole[AssumeRole API]. The AssumeRole function provides short-term credentials for enhanced security and flexible access control.

* *QUESTION: Not mentioned in docs?* Quality of service (QoS): 2,500 traffic classifiers enable detailed traffic management to ensure consistent performance.

* *QUESTION: New for 12.0?* Per-bucket object count quota allows for better control and management of storage resources. 

== Security 
* Stronger data encryption and integrity protection provide improved security and performance. 

* Increased security of stored passwords reduce the risk of unauthorized access. 

* link:../admin/manage-ssh-access.html[SSH is blocked by default] to enhance security while allowing controlled access. 

== User interface

* Dark theme and system theme settings are available in the User menu of the Grid Manager and Tenant Manager.

* Audit and syslog server page refactored, with additions for storing logs in a system bucket for backup purposes.

* The legacy Grid Topology page was removed. Over the past several StorageGRID releases, the operations and metrics available from that page were migrated to other pages in the Grid Manager.
