---
permalink: tenant/enable-cross-origin-resource-sharing-cors.html
sidebar: sidebar
keywords: how to configure cross-origin resource sharing, cors
summary: 'You can configure cross-origin resource sharing \(CORS\) for an S3 bucket if you want that bucket and objects in that bucket to be accessible to web applications in other domains.'
---
= Enable StorageGRID CORS for a management interface 
:icons: font
:imagesdir: ../media/

[.lead]
You can enable cross-origin resource sharing (CORS) for management API requests to a StorageGRID domain if you want data in the StorageGRID domain to be accessible to another domain at the management interface level.

.Before you begin

* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* The link:tenant-management-permissions.html[Root access permission] provides access to all CORS configuration requests.

.About this task

Cross-origin resource sharing (CORS) is a security mechanism that allows client web applications in one domain to access resources in a different domain. For example, you have data in a StorageGRID domain that you want to make accessible to build a Grid Manager in domain `\http://www.example.com`. By enabling CORS in the StorageGRID domain for `\http://www.example.com` for "Grid Manager", the StorageGRID domain responds to Grid Management API requests from `\http://www.example.com`.  

The following support is available for CORS at the management interface level:

* Management API (mgmt-api) requests
* Support for `application/json` and `multipart/formdata` requests for `Content-Type`

.Steps

. Under *Network* on the StorageGRID Configuration page, select *Management interface CORS settings*.
. Select *Grid Manager*, *Tenant Manager*, or both options.
* *Grid Manager*: Enables CORS for cross-domain Grid Management API requests.  
* *Tenant Manager*: Enables CORS for cross-domain Tenant Management API requests.
* *Both options*: Enables CORS for cross-domain Grid Management and Tenant Management API requests.
. Enter the URL for the other domain in the *Domains* field.
+
Select *Add another domain* if you want to enable CORS in StorageGRID for more than one domain.

// 2025 MAR 12, SGWS-34427