---
permalink: tenant/manage-branch-buckets.html
sidebar: sidebar
keywords: how to create branch bucket
summary: 'A branch bucket provides access to objects in a bucket as they existed at a certain time. Use the Tenant Manager to create and view branch buckets.'
---
= Manage branch buckets
:icons: font
:imagesdir: ../media/

[.lead]
A branch bucket provides access to objects in a bucket as they existed at a certain time. Use the Tenant Manager to create and view branch buckets.

.About this task
You create a branch bucket from an existing bucket. After you create a branch bucket, the original bucket it was created from is called the base bucket. When you perform operations on the base bucket, the results on the branch bucket depend on the operation and the type of branch bucket you've created.

You can use a branch bucket to remove corrupt objects by creating a branch bucket from a point in time before the corruption occurred, and then pointing applications to the branch bucket instead of to the base bucket that contains corrupt objects.

Machine learning?

Code version control?

CAUTION: A branch bucket doesn't serve as a backup, but provides access to protected data. You must continue to use link:../ilm/managing-objects-with-s3-object-lock.html[S3 Object Lock] or link:../admin/grid-federation-what-is-cross-grid-replication.html[cross-grid replication] to protect data.

.Before you begin

* The base bucket you want to create a branch from has versioning enabled.
* You are signed in to the Tenant Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You belong to a user group that has the Root access or Manage all buckets link:tenant-management-permissions.html[permission]. These permissions override the permissions settings in group or bucket policies. 
+
NOTE: Permissions to set or modify S3 Object Lock properties of buckets or objects can be granted by link:../s3/bucket-and-group-access-policies.html[bucket policy or group policy].

== Create branch bucket

.Steps

. Select *View buckets* from the dashboard, or select  *STORAGE (S3)* > *Buckets*.

. Select the bucket you want to create a branch from.

. On the bucket details page, select *Create branch bucket*.

== Enter details

.Steps

. Enter details for the branch bucket.
+
[cols="1a,3a" options="header"]
|===

| Field | Description

| Branch bucket name
| A name for the branch bucket that complies with these rules:

* Must be unique across each StorageGRID system (not just unique within the tenant account).
* Must be DNS compliant.
* Must contain at least 3 and no more than 63 characters.
* Each label must start and end with a lowercase letter or a number and can only use lowercase letters, numbers, and hyphens.
* Must not contain periods in virtual hosted style requests. Periods will cause problems with server wildcard certificate verification.

For more information, see the https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html[Amazon Web Services (AWS) documentation on bucket naming rules^].

*Note*: You can't change the name after creating the branch bucket.

| Region 
| The branch bucket's region.

Your StorageGRID administrator manages the available regions. A bucket's region can affect the data-protection policy applied to objects. By default, all buckets are created in the `us-east-1` region.

*Note*: You can't change the region after creating the branch bucket.

| Before time
| The branch bucket provides access to object versions created in the base bucket earlier than the Before time.

| Branch bucket type
|
* *Read-write*: You can modify the contents and settings of the branch bucket. For example, you can add new objects or object versions to the branch bucket, and you can modify settings such as bucket policies.

* *Read-only*: You can't modify the branch bucket. It will contain only objects and settings from the base bucket. 
|===

. Select *Continue*.

== Manage settings

The settings for a branch bucket don't affect the object versions in the base bucket.

.Steps

. If the global S3 Object Lock setting is enabled, optionally enable S3 Object Lock for the branch bucket. To enable S3 Object Lock, the branch bucket must be a read-write bucket.
+
Enable S3 Object Lock for a branch bucket only if you need to keep objects for fixed amount of time, for example, to meet certain regulatory requirements. S3 Object Lock is a permanent setting that helps you prevent objects from being deleted or overwritten for a fixed amount of time or indefinitely. 
+
CAUTION: After the S3 Object Lock setting is enabled for a bucket, it can't be disabled. Anyone with the correct permissions can add objects to this bucket that can't be changed. You might not be able to delete these objects or the bucket itself.
+
If you enable S3 Object Lock for a bucket, bucket versioning is enabled automatically.

. If you selected *Enable S3 Object Lock*, optionally enable *Default retention* for this bucket.
+
NOTE: Your grid administrator must give you permission to link:../tenant/using-s3-object-lock.html[use specific features of S3 Object Lock].
+
When *Default retention* is enabled, new objects added to the bucket will be automatically protected from being deleted or overwritten. The *Default retention* setting does not apply to objects that have their own retention periods.

.. If *Default retention* is enabled, specify a *Default retention mode* for the bucket.
+
include::../_include/bucket-governance-compliance.adoc[]

.. If *Default retention* is enabled, specify the *Default retention period* for the bucket.
+
The *Default retention period* indicates how long new objects added to this bucket should be retained, starting from the time they are ingested. Specify a value that is less than or equal to the maximum retention period for the tenant, as set by the grid administrator.
+
A _maximum_ retention period, which can be a value from 1 day to 100 years, is set when the grid administrator creates the tenant. When you set a _default_ retention period, it can't exceed the value set for the maximum retention period. If needed, ask your grid administrator to increase or decrease the maximum retention period.

. [[capacity-limit]]Optionally, select *Enable capacity limit*.
+
Capacity limit is the maximum capacity available for this bucket's objects. This value represents a logical amount (object size), not a physical amount (size on disk).
+
If no limit is set, the capacity for this bucket is unlimited. Refer to link:../tenant/understanding-tenant-manager-dashboard.html#bucket-capacity-usage[Capacity limit usage] for more information.

. Optionally, select *Enable object count limit*.
+
Object count limit is the maximum number of objects the branch bucket can contain. This value represents a logical amount (object count). If no limit is set, the object count is unlimited.

. Select *Create bucket*.
+
The branch bucket is created and added to the table on the Buckets page.

. Optionally, select *Go to bucket details page* to link:viewing-s3-bucket-details.html[view branch bucket details] and perform additional configuration.

== Branch bucket operations and settings

You can create a branch bucket from an existing branch bucket.

If you delete objects in a branch bucket, the base bucket objects won't be affected.

Cross-grid replication and platform services aren't supported in StorageGRID 12.0