---
permalink: rhel/downloading-and-extracting-storagegrid-installation-files.html
sidebar: sidebar
keywords: red hat linux installation files, how to download installation files
summary: 'You must download the StorageGRID installation archive and extract the required files.'
---
= Download and extract the StorageGRID installation files
:icons: font
:imagesdir: ../media/

[.lead]
You must download the StorageGRID installation archive and extract the required files.

.Steps

. Go to the https://mysupport.netapp.com/site/products/all/details/storagegrid/downloads-tab[NetApp Downloads page for StorageGRID^].
. Select the button for downloading the latest release, or select another version from the drop-down menu and select *Go*.
. Sign in with the username and password for your NetApp account.
. If a Caution/MustRead statement appears, read it and select the checkbox.
+
CAUTION: You must apply any required hotfixes after you install the StorageGRID release. For more information, see the link:../maintain/storagegrid-hotfix-procedure.html[hotfix procedure in the recovery and maintenance instructions].

. Read the End User License Agreement, select the checkbox, and then select *Accept & Continue*.
. In the *Install StorageGRID* column, select the .tgz or .zip file for Red Hat Enterprise Linux.
+
NOTE: Select the `.zip` file if you are running Windows on the service laptop.

. Save the archive file.
. Manually the verify downloaded artifacts.
+
Downloaded artifacts::
+
* Leaf certificate: `signatures/Leaf-Cert.pem`
* Certificate chain: `signatures/CA-Int-Cert.pem`
* Time stamp response chain: `TS-Cert.pem`
* Checksum file: `sha256sum`
* Checksum signature: `signatures/sha256sum.sig`
* Time stamp response file: `signatures/sha256sum.sig.tsr`

Verfication steps::

.. Use the chain to verify the leaf certificate is valid.
+
*Example*: `openssl verify -CAfile signatures/CA-Int-Cert.pem signatures/Leaf-Cert.pem`
+
*Expected output*: `signatures/Leaf-Cert.pem: OK`
.. If step _a_ failed because of an expired leaf certificate, use the `tsr` file to verify.
+
*Example*: `openssl ts -CAfile signatures/CA-Int-Cert.pem -untrusted signatures/TS-Cert.pem -verify -data signatures/sha256sum.sig -in signatures/sha256sum.sig.tsr`
+
*Expected output includes*: `Verification: OK`
.. Create a public key file from the leaf certificate.
+
*Example*: `openssl x509 -pubkey -noout -in signatures/Leaf-Cert.pem > signatures/Leaf-Cert.pub`
+
*Expected output*: _none_
.. Use the public key to verify the `sha256sum` file against `signatures/sha256sum.sig`.
+
*Example*: `openssl dgst -sha256 -verify signatures/Leaf-Cert.pub -signature signatures/sha256sum.sig sha256sum`
+
*Expected output*: `Verified OK`
.. Verify the `sha256sum` file content against newly created checksums.
+
*Example*: `sha256sum -c sha256sum`
+
*Expected output*: `_<filename>_: OK`

. Extract the files from the archive.

. Choose the files you need from the following list.
+
The files you need depend on your planned grid topology and how you will deploy your StorageGRID system.
+
NOTE: The paths listed in the table are relative to the top-level directory installed by the extracted installation archive

include::../_include/installation-files-rhel.adoc[]
