---
permalink: admin/change-node-console-password.html
sidebar: sidebar
keywords: node console password, console password, change password, password
summary: 'Each node in your grid has a node console password, which you use to log in to the node. By default, each node has a unique password. You can change each password to a new unique password, or you can change the password for every node to use a global password. The passwords are stored in the recovery package.'
---
= Change node console passwords
:icons: font
:imagesdir: ../media/

[.lead]
Each node in your grid has a node console password, which you use to log in to the node. By default, each node has a unique password. You can change each password to a new unique password, or you can change the password for every node to use a global password. The passwords are stored in the recovery package.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:admin-group-permissions.html[Maintenance or Root access permission].
* You have the current provisioning passphrase.

.About this task

You use a node console password to log in to a node as "admin" using SSH, or to the root user on a VM/physical console connection. You can change node console passwords using one of these options:

* Automatically apply random passwords to each node
* Specify and apply one global password to all nodes
* Specify and apply a unique password to one or more nodes

The passwords are stored in an updated `Passwords.txt` file in the recovery package. The passwords are listed in the Password column in the file. 

NOTE: The link:../admin/change-ssh-access-passwords.html[SSH access passwords] for the SSH keys used for communication between nodes are separate from the node console passwords. This procedure doesn't change the SSH access passwords.

== Access the wizard

.Steps
. Select *CONFIGURATION* > *Access control* > *Grid passwords*.

. Under *Change node console passwords*, select *Make a change*.

== [[download-current]]Download the current recovery package

Before changing node console passwords, download the current recovery package. You can use the passwords in this file if the password change process fails for any node.

.Steps

. Enter the provisioning passphrase for your grid.

. Select *Download recovery package*.

. Copy the recovery package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: The recovery package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select *Continue*.

== Provide new passwords

. Select the password change method you want to use.
+
* *Automatic*: StorageGRID automatically assigns a new random console password to all nodes.
* *Custom*: You provide console passwords.

[role="tabbed-block"]
====
.Automatic
--
If you selected *Automatic*:

. Select *Continue*.
--
//end Automatic, begin Custom

.Custom
--
If you selected *Custom*:

. Select one of the following:
+
* *Global console password*: Apply the same console password to all nodes.
* *Unique console passwords*: Apply a different password on one or more nodes.
. If you selected *Global console password*, enter the password you want to use for all nodes.
. If you selected *Unique console passwords*, enter a unique password for one or more nodes.
. Select *Continue*.
--
====
//end tabbed blocks

== Complete the password change process

. When the confirmation dialog appears, select *Yes* if you are ready for StorageGRID to start changing the node console passwords.
+
NOTE: You can't cancel this process after it starts.
+
StorageGRID generates a new recovery package containing the new password.
. When the new recovery package is ready, select *Download new recovery package* and save the recovery package.
. Open the `.zip` file.
. Confirm that you can access the contents, including the `Passwords.txt` file, which contains the new node console passwords.
. Copy the new recovery package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: Don't overwrite the old recovery package.
+
You must secure the recovery file, because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.
. Select the checkbox to indicate you've downloaded the new recovery package and verified the content.
. Select *Continue*.
+
StorageGRID updates the password for each node.
+
If there is an error during the update process, the progress bar lists the number of nodes that failed to have their passwords changed. The system will automatically retry the process on any node that failed to have its password changed. If the process ends with some nodes still not having a changed password, the *Retry* button appears.
+
. If the password update failed for one or more nodes: 
.. Review the error messages listed in the table.
.. Resolve the issues.
.. Select *Retry*.
+
NOTE: Retrying only changes the node console passwords on the nodes that failed during previous password change attempts. 
. When the progress bar indicates that no updates are remaining, select *Finish*.
. After node console passwords have been changed for all nodes, delete the <<download-current,first recovery package you downloaded>>.