---
permalink: admin/change-ssh-access-keys.html
sidebar: sidebar
keywords: ssh access keys, change ssh access keys
summary: 'Each node in your grid has a unique SSH access key, which the nodes use to access each other. Changing this access key also updates the internal SSH keys, which the primary Admin Node uses to access nodes. Save a Recovery Package before and after you make the change.'
---
= Change SSH access keys
:icons: font
:imagesdir: ../media/

[.lead]
Each node in your grid has a unique SSH access key, which the nodes use to access each other. Changing this access key also updates the internal SSH keys, which the primary Admin Node uses to access nodes. Save a Recovery Package before and after you make the change.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:admin-group-permissions.html[Maintenance or Root access permission].
* You have the current provisioning passphrase.

.About this task

You use the SSH key to log in to a node as `admin` or to the root user on a VM/physical console connection. The change SSH access key process creates new keys for each node in your grid and stores the keys in an updated `Passwords.txt` file in the Recovery Package. The keys are listed in the Password column in the `Passwords.txt` file.

NOTE: There are separate SSH access passwords for the SSH keys used for communication between nodes. The SSH access passwords aren't changed by this procedure.

== Access the wizard

.Steps
. Select *CONFIGURATION* > *Access control* > *Grid passwords*.

. Under *Change SSH keys*, select *Make a change*.

== [[download-current]]Download the current recovery package

Before changing SSH access keys, download the current Recovery Package. You can use the keys in this file if the key change process fails for any node.

.Steps

. Enter the provisioning passphrase for your grid.

. Select *Download recovery package*.

. Copy the Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select *Continue*.

. When the confirmation dialog appears, select *Yes* if you are ready to start changing the SSH access keys.
+
CAUTION: You can't cancel this process after it starts.

== Change SSH access keys

When the change SSH access keys process starts, a new Recovery Package is generated that includes the new keys. Then, the keys are updated on each node.

.Steps

. Wait for the new Recovery Package to be generated, which might take a few minutes.

. Select *Download new recovery package*. 

. When the download completes:

.. Open the `.zip` file.
.. Confirm that you can access the contents, including the `Passwords.txt` file, which contains the new SSH access keys.
.. Copy the new Recovery Package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: Don't overwrite the old Recovery Package.
+
The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

. Select the checkbox to indicate you have downloaded the new Recovery Package and verified the content.

. Select *Change SSH access keys* and wait for all nodes to be updated with the new keys. This might take a few minutes.
+
If keys are changed for all nodes, a green success banner appears. Go to the next step.
+
If there is an error during the update process, a banner message lists the number of nodes that failed to have their keys changed. The system will automatically retry the process on any node that failed to have its key changed. If the process ends with some nodes still not having a changed key, the *Retry* button appears.
+
If the key update failed for one or more nodes: 

.. Review the error messages listed in the table.
.. Resolve the issues.
.. Select *Retry*.
+
Retrying only changes the SSH access keys on the nodes that failed during previous key change attempts. 

. After SSH access keys have been changed for all nodes, delete the <<download-current,first Recovery Package you downloaded>>.

. Optionally, use the *Recovery package* link to download an additional copy of the new Recovery Package.