---
permalink: admin/creating-enterprise-application-entra.html
sidebar: sidebar
keywords: enterprise application, entra id, single sign on, sso
summary: 'You use Entra ID to create an enterprise application for each Admin Node in your system.'
---
= Create enterprise applications in Entra ID
:icons: font
:imagesdir: ../media/

[.lead]
You use Entra ID to create an enterprise application for each Admin Node in your system.

.Before you begin

* You have started configuring single sign-on for StorageGRID and you selected *Entra* as the SSO type.

* You have link:../admin/configure-sso.html#enter-sandbox-mode[entered sandbox mode] in Grid Manager.

* You have the *Enterprise application name* for each Admin Node in your system. You can copy these values from the Admin Node details table on the Configure SSO page.
+
NOTE: You must create an enterprise application for each Admin Node in your StorageGRID system. Having an enterprise application for each Admin Node ensures that users can securely sign in to and out of any Admin Node.

* You have experience creating enterprise applications in Entra Active Directory.

* You have an Entra account with an active subscription.

* You have one of the following roles in the Entra account: Global Administrator, Cloud Application Administrator, Application Administrator, or owner of the service principal.

== Access Entra ID

.Steps

. Log in to the https://portal.azure.com[Entra Portal^].

. Navigate to https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade[Entra Active Directory^].

. Select https://portal.azure.com/#blade/Microsoft_AAD_IAM/StartboardApplicationsMenuBlade/Overview/menuId/[Enterprise applications^].

== Create enterprise applications and save StorageGRID SSO configuration

To save the SSO configuration for Entra in StorageGRID, you must use Entra to create an enterprise application for each Admin Node. You will copy the federation metadata URLs from Entra and paste them into the corresponding *Federation metadata URL* fields on the Configure SSO page. 

.Steps

. Repeat the following steps for each Admin Node.

.. In the Entra Enterprise applications pane, select *New application*.

.. Select *Create your own application*.

.. For the name, enter the *Enterprise application name* you copied from the Admin Node details table on the Configure SSO page.

.. Leave the *Integrate any other application you don't find in the gallery (Non-gallery)* radio button selected.

.. Select *Create*.

.. Select the *Get started* link in the *2. Set up single sign on* box, or select the *Single sign-on* link in the left margin.

.. Select the *SAML* box.

.. Copy the *App Federation Metadata Url*, which you can find under *Step 3 SAML Signing Certificate*. 

.. Go to the Configure SSO page, and paste the URL in the *Federation metadata URL* field that corresponds to the *Enterprise application name* you used.

. After you have pasted a federation metadata URL for each Admin Node and made all other needed changes to the SSO configuration, select *Save* on the Configure SSO page.

== Download SAML metadata for every Admin Node
After the SSO configuration is saved, you can download a SAML metadata file for each Admin Node in your StorageGRID system. 

.Steps

. Repeat these steps for each Admin Node.
 
.. Sign in to StorageGRID from the Admin Node.
.. Select *CONFIGURATION* > *Access control* > *Single sign-on*.
.. Select the button to download the SAML metadata for that Admin Node. 
.. Save the file, which you will upload into Entra ID.

== Upload SAML metadata to each enterprise application

After downloading a SAML metadata file for each StorageGRID Admin Node, perform the following steps in Entra ID:

.Steps

. Return to the Entra Portal.
. Repeat these steps for each enterprise application:
+
NOTE: You might need to refresh the Enterprise applications page to see applications you previously added in the list.

.. Go to the Properties page for the enterprise application.
.. Set *Assignment required* to *No* (unless you want to separately configure assignments).
.. Go to the Single sign-on page.
.. Complete the SAML configuration.
.. Select the *Upload metadata file* button and select the SAML metadata file you downloaded for the corresponding Admin Node. 
.. After the file loads, select *Save* and then select *X* to close the pane. You are returned to the Set up Single Sign-On with SAML page. 

. link:../admin/configure-sso-html#test-sso[Test each application].


