---
permalink: admin/creating-sp-connection-ping-oidc.html
sidebar: sidebar
keywords: service provider, sp connection, pingfederate, ping, single sign on, sso
summary: 'You use PingFederate to create a service provider (SP) connection for each Admin Node in your system. To speed the process, you will import the SAML metadata from StorageGRID.'
---
= Create service provider (SP) connections in PingFederate for OIDC
:icons: font
:imagesdir: ../media/

[.lead]
You use PingFederate to create a service provider (SP) connection for each Admin Node in your system. To speed up the process, you will import the SAML metadata from StorageGRID.

.Before you begin

* You have configured single sign-on for StorageGRID and you selected *Ping Federate* as the SSO type.

* You have link:../admin/configure-sso-oidc.html#enter-sandbox-mode[entered sandbox mode] in Grid Manager.

* You have the *SP connection ID* for each Admin Node in your system. You can find these values in the Admin Nodes detail table on the Configure SSO page.

* You have experience creating SP connections in PingFederate Server.

* You have the
https://docs.pingidentity.com/pingfederate/latest/administrators_reference_guide/pf_administrators_reference_guide.html[Administrator's Reference Guide^] for PingFederate Server. The PingFederate documentation provides detailed step-by-step instructions and explanations.

* You have the link:../admin/admin-group-permissions.html[Admin permission] for PingFederate Server.

.About this task
These instructions summarize how to configure PingFederate Server version 10.3 as an SSO provider for StorageGRID. If you are using another version of PingFederate, you might need to adapt these instructions. Refer to the PingFederate Server documentation for detailed instructions for your release.
