---
permalink: admin/creating-enterprise-application-entra-id-oidc.html
sidebar: sidebar
keywords: enterprise application, entra id, single sign on, sso
summary: 'You use Entra ID to create an application for each Admin Node in your system.'
---
= Create applications in Entra ID for OIDC
:icons: font
:imagesdir: ../media/

[.lead]
You use Entra ID to create an enterprise application for each Admin Node in your system.

.Before you begin

* You have started configuring single sign-on for StorageGRID and you selected *Entra ID* as the SSO type.

* You have link:../admin/configure-sso-oidc.html#enter-sandbox-mode[entered sandbox mode] in Grid Manager.

* You have the *Relying party identifier*, *OpenID endpoint URL*, and *Client secret* for each Admin Node in your system. You can copy these values from the Admin Node details table on the Configure SSO page.
+
NOTE: You must create an application for each Admin Node in your StorageGRID system. Having an application for each Admin Node ensures that users can securely sign in to and out of any Admin Node.

* You have experience creating applications in Entra ID.

* You have an Entra ID account with an active subscription.

* You have one of the following roles in the Entra ID account: Global Administrator, Cloud Application Administrator, Application Administrator, or owner of the service principal.

== Step 1: Access Entra ID

.Steps

. Log in to the https://portal.azure.com[Azure Portal^].

. Select the *StorageGRID VTC* organizational directory.

== Step 2: Register a new application

Register a new application for each Admin Node in your system. 

.Steps

. In the Entra ID Enterprise applications pane, select *Application registrations*.
. Select *New registration*.
. For the name, enter the *Relying party identifier* that you copied from the Admin Node details table on the Configure SSO page.
. Select *Accounts in this organizational directory only (StorageGRID VTC only - Single tenant)*.
. Enter the *OpenID endpoint URL* that you copied from the Admin Node details table on the Configure SSO page.
. Select *Register*.
. Navigate to the overview page for the new application registration.
. Record the *Application (client) ID* and *Directory (tenant) ID* values for the new application.

== Step 3: Configure a client secret

Register a client secret for each new application.

.Steps

. In the overview page of the new application registration, select *Certificates and secrets* > *New client secret*.
. Enter the *Client secret* that you copied from the Admin Node details table on the Configure SSO page.
. Set a desired expiry date.
. Select *Add* to create the client secret.
. Copy the *(Secret) Value*.
+
NOTE: If you refresh or navigate away from the client secret page, you can't copy the secret value.

== Step 4: Set up the API permissions 

Set up the API permissions for each new application.

.Steps

. In the overview page of the new application registration, select *API permissions* > *Add a permission*.
. Select the *Microsoft APIs* tab, then select *Microsoft Graph* for the API.
. Select *Delegated permissions* for the permissions type.
. Expand *OpenId permissions*, then select *email*, *offline_access*, *openid*, and *profile*.
. Select *Add permissions*.
. Select *Grant admin consent for StorageGRID VTC*, then select *Yes* to confirm.

// 2026 MAR 31, SGWS-39432