---
permalink: admin/grid-federation-automate-connections.html
sidebar: sidebar
keywords: automate, automating, automation, automatic, configuration, configure
summary: "You can automate the establishment of grid federation connections among a group of grid nodes in the StorageGRID system. Automation prepares these connections so you don't have to create connections manually for each unique pair of grid nodes."
---
= Automate grid federation connections in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can automate the establishment of grid federation connections among a group of grid nodes in the StorageGRID system. Automation prepares these connections so you don't have to create connections manually for each unique pair of grid nodes.

.Before you begin

* You know the location of the following files from the installation archive.
+
[cols="1a,1a" options="header"]
|===
| Filename| Description
m| configure-storagegrid.py
| Python script used to automate the configuration

m| configure-storagegrid.sample.json
| Example configuration file for use with the script

m| configure-storagegrid.blank.json
| Blank configuration file for use with the script
|===

* You have created a `configure-storagegrid.json` configuration file. To create this file, you can modify the example configuration file (`configure-storagegrid.sample.json`) or the blank configuration file (`configure-storagegrid.blank.json`).

CAUTION: Store the management password and provisioning passphrase from the passwords section of the modified `configure-storagegrid.json` configuration file in a secure location. These passwords are required for installation, expansion, and maintenance procedures. You should also back up the modified `configure-storagegrid.json` configuration file and store it in a secure location.

.About this task

You can use the `configure-storagegrid.py` Python script and the `configure-storagegrid.json` configuration file to automate the configuration of your StorageGRID system.

NOTE: You can also configure the system using the https://docs.netapp.com/us-en/storagegrid/primer/exploring-grid-manager.html[Grid Manager^] or the link:overview-of-installation-rest-apis.html[Installation API].

.Steps

. Log in to the Linux machine you are using to run the Python script.
. Change to the directory where you extracted the installation archive.
+
For example: +
`cd StorageGRID-Webscale-_version/platform_`
+
where `_platform_` is `debs`, `rpms`, or `vsphere`.

. Run the Python script and use the configuration file you created.
+
For example:
+
----
./configure-storagegrid.py ./configure-storagegrid.json --start-install
----

.After you finish

A Recovery Package `.zip` file is generated during the configuration process, and it is downloaded to the directory where you are running the installation and configuration process. You must back up the Recovery Package file so that you can recover the StorageGRID system if one or more grid nodes fails. For example, copy it to a secure, backed up network location and to a secure cloud storage location.

CAUTION: The Recovery Package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.

If you specified that random passwords should be generated, you need to extract the `Passwords.txt` file and look for the passwords required to access your StorageGRID system.

----
######################################################################
##### The StorageGRID "recovery package" has been downloaded as: #####
#####           ./sgws-recovery-package-994078-rev1.zip          #####
#####   Safeguard this file as it will be needed in case of a    #####
#####                 StorageGRID node recovery.                 #####
######################################################################
----

Your StorageGRID system is installed and configured when a confirmation message is displayed.

----
StorageGRID has been configured and installed.
----
