---
permalink: admin/manage-ssh-access.html
sidebar: sidebar
keywords: security, external, ssh, access
summary: 'You can manage SSH protection by enabling or disabling external SSH access.'
---
= Manage external SSH access
:icons: font
:imagesdir: ../media/

[.lead]
You can manage SSH protection by enabling or disabling external SSH access.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:admin-group-permissions.html[Root access permission].

.About this task

External SSH access is disabled by default. NetApp recommends keeping this access disabled to enhance system security. You can enable external SSH access when it’s required, for example, to perform troubleshooting tasks. 

.Steps
. Select *CONFIGURATION* > *Security* > *Security settings*.
. Select the *Block SSH* tab.
. Use the *Block inbound SSH access* option to manage external SSH access:
.. Select the checkbox to block access (default).
.. Unselect the checkbox to allow access.
. Select *Save*.

// 2025 APR 22, SGWS-35048