---
permalink: admin/manage-mav-protected-ops-requests.html
sidebar: sidebar
keywords: multi-admin verification, mav
summary: "As a MAV administrator, you can manage requests for MAV-protected operations in StorageGRID. You can view your own or others' pending requests, approve or reject requests, and view the history of past requests."
---
= Manage MAV-protected operations requests in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
As a MAV administrator, you can manage requests for MAV-protected operations in StorageGRID. You can view your own or others' pending requests, approve or reject requests, and view the history of past requests.

.Before you begin
* You have the link:../admin/admin-group-permissions.html[Multi-admin verification requests or Root access permission].
* You're signed in to the Grid Manager from the primary Admin Node.

.Steps
. To manage MAV-protected operations requests:
+
* If you receive an email notification, select the link in the email to view the MAV request details.

* If MAV isn't configured to send email notifications, check for pending requests on the Grid Manager dashboard or by selecting *Configuration* > *Multi-admin verification* > *My requests* or *Configuration* > *Multi-admin verification* > *Other requests*.

. Select the radio button for each request you want to manage.

. Select *Approve* or *Reject* to approve or reject the selected requests.

. To view a history of past requests, select *History*.

