---
permalink: admin/request-mav-approval-for-protected-ops.html
sidebar: sidebar
keywords: multi-admin verification, mav
summary: 'As a StorageGRID administrator or user, when you initiate a MAV-protected operation in StorageGRID, a request is generated automatically. A message appears to inform you that the operation requires approval.'
---
= Request approval for MAV-protected operations in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
As a StorageGRID administrator or user, when you initiate a MAV-protected operation in StorageGRID, a request is generated automatically. A message appears to inform you that the operation requires approval.

The StorageGRID system defines which operations are protected by MAV. When you initiate a MAV-protected operation, the request is sent to the MAV administrators for approval.

.Steps

. The StorageGRID system informs you that you've initiated a MAV-protected operation.

. Check the status of your request by selecting *Configuration* > *Access control* > *Multi-admin verification* > *My requests*.

. Check for pending requests by selecting *Configuration* > *Access control* > *Multi-admin verification* > *Other requests*.

. To cancel an operation, select the corresponding request and then select *Withdraw*. You can also select *Withdraw* in the My requests tab.

. After a MAV administrator approves the request, the operation is performed automatically.
+
If your request is rejected, the operation isn't performed, and you can submit a new request if needed.

.MAV request statuses

Pending:: Request has been initiated.

Expired:: Request wasn't addressed within 30 days. Or a user with Root access permission disabled MAV, which mean all pending requests expire.

Withdrawn:: A user withdrew their request.

Approved:: A MAV administrator approved the pending request.

Rejected:: A MAV administrator rejected the pending request.
