---
permalink: s3/index.html
sidebar: sidebar
keywords: about s3, s3 rest api, s3 overview
summary: "StorageGRID supports the Simple Storage Service (S3) API, which is implemented as a set of Representational State Transfer (REST) web services."
---
= StorageGRID S3 REST API supported versions and updates
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID supports the Simple Storage Service (S3) API, which is implemented as a set of Representational State Transfer (REST) web services.

Support for the S3 REST API enables you to connect service-oriented applications developed for S3 web services with on-premise object storage that uses the StorageGRID system. Minimal changes to a client application's current use of S3 REST API calls are required.

== Supported versions

StorageGRID supports the following specific versions of STS, S3 and HTTP:

[cols="1a,1a" options="header"]
|===
| Item| Version

| STS AssumeRole API specification
| https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html[Amazon Web Services (AWS) documentation: Amazon Assumerole API Reference^]

For more information about AssumeRole, refer to link:../tenant/manage-groups.html#set-up-assumerole[Set up AssumeRole].


| S3 API specification
| http://docs.aws.amazon.com/AmazonS3/latest/API/Welcome.html[AWS documentation: Amazon Simple Storage Service API Reference^]


| HTTP
| 1.1

For more information about HTTP, see HTTP/1.1 (RFCs 7230-35).

https://datatracker.ietf.org/doc/html/rfc2616[IETF RFC 2616: Hypertext Transfer Protocol (HTTP/1.1)^]

*Note*: StorageGRID does not support HTTP/1.1 pipelining.

|===

[[updates-to-rest-api-support]]
== Updates to S3 REST API support

include::../_include/s3-rest-api-updates.adoc[]

// 2025-05-07, SGWS 34003