---
permalink: monitor/access-snmp-mib.html
sidebar: sidebar
keywords: mib, snmp, monitoring
summary: 'MIB files contain definitions and information about the properties of managed resources and services for the nodes in your grid. You can access MIB files that define the objects and notifications for StorageGRID. These files can be useful for monitoring your grid.'
---
= Access MIB files
:icons: font
:imagesdir: ../media/

[.lead]
MIB files contain definitions and information about the properties of managed resources and services for the nodes in your grid. You can access MIB files that define the objects and notifications for StorageGRID. These files can be useful for monitoring your grid.

See link:using-snmp-monitoring.html[Use SNMP monitoring] for more information about SNMP and MIB files. 

== Access MIB files

Follow these steps to access the MIB files.

.Steps

. Select *CONFIGURATION* > *Monitoring* > *SNMP agent*.
. On the SNMP agent page, select the file you want to download:
+
* *NETAPP-STORAGEGRID-MIB.txt*: Defines the alert table and notifications (traps) accessible on all Admin Nodes.
* *ES-NETAPP-06-MIB.mib*: Defines objects and notifications for E-Series-based appliances.
* *MIB_1_10.zip*: Defines objects and notifications for appliances with a BMC interface.
+
TIP: You can also access MIB files at the following location on any StorageGRID node: `/usr/share/snmp/mibs`

. To extract the StorageGRID OIDs from the MIB file:

.. Get the OID of the root of the StorageGRID MIB:
+
`root@user-adm1:~ # snmptranslate -On -IR storagegrid`
+
Result: `.1.3.6.1.4.1.789.28669` (`28669` is always the OID for StorageGRID)

.. Grep for the StorageGRID OID in the entire tree (using `paste` to join lines): 
+
`root@user-adm1:~ # snmptranslate -Tso | paste -d " " - - | grep 28669`
+
TIP: The `snmptranslate` command has many options that are useful for exploring the MIB. This command is available on any StorageGRID node.

== MIB file contents

All objects are under the StorageGRID OID.

[cols="1a,1a,2a" options="header"]
|===
| Object name| Object ID (OID)| Description

m| .iso.org.dod.internet. +
private.enterprises. +
netapp.storagegrid
m| .1.3.6.1.4.1.789.28669
| The MIB module for NetApp StorageGRID entities.
|===

== MIB objects

[cols="1a,1a,1a,1a,1a,2a" options="header"]
|===
| Object name| Object ID (OID) | Type | Access | MIB module | Description

m| activeAlertCount
m| .1.3.6.1.4.1. +
789.28669.1.3
| Integer32
| Read-only
| NETAPP-STORAGEGRID-MIB
| The number of active alerts in the activeAlertTable.

m| activeAlertTable
m| .1.3.6.1.4.1. +
789.28669.1.4
| Sequence of ActiveAlertEntry
| Not-accessible
| NETAPP-STORAGEGRID-MIB
| A table of active alerts in StorageGRID.

m| activeAlertEntry
m| .1.3.6.1.4.1. +
789.28669.1.4.1
| Sequence
| Not-accessible
| NETAPP-STORAGEGRID-MIB
| A single StorageGRID alert, indexed by alert ID.

m| activeAlertId
m| .1.3.6.1.4.1. + 
789.28669.1.4.1.1
| Octet string
| Read-only
| NETAPP-STORAGEGRID-MIB
| The ID of the alert. Only unique in the current set of active alerts.

m| activeAlertName
m| .1.3.6.1.4.1. +
789.28669.1.4.1.2
| Octet string
| Read-only
| NETAPP-STORAGEGRID-MIB
| The name of the alert.

m| activeAlertInstance
m| .1.3.6.1.4.1. +
789.28669.1.4.1.3
| Octet string
| Read-only
| NETAPP-STORAGEGRID-MIB
| The name of the entity that generated the alert, typically the node name.

m| activeAlertSeverity
m| .1.3.6.1.4.1. +
789.28669.1.4.1.4
| Octet string
| Read-only
| NETAPP-STORAGEGRID-MIB
| The severity of the alert.

m| activeAlertStartTime
m| .1.3.6.1.4.1. + 
789.28669.1.4.1.5
| Date and time
| Read-only
| NETAPP-STORAGEGRID-MIB
| The time the alert was triggered.
|===

// 2025 JULY 4, SGRIDDOC-168