---
permalink: monitor/collecting-log-files-and-system-data.html
sidebar: sidebar
keywords: how to collect system data, how to collect logs
summary: 'You can use the Grid Manager to retrieve log files and system data \(including configuration data\) for your StorageGRID system.'
---
= Collect log files and system data
:icons: font
:imagesdir: ../media/

[.lead]
You can use the Grid Manager to retrieve log files and system data (including configuration data) for your StorageGRID system.

.Before you begin
* You must be signed in to the Grid Manager on the primary Admin Node using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[specific access permissions].
* You must have the provisioning passphrase.

.About this task
You can use the Grid Manager to gather link:logs-files-reference.html[log files], system data, and configuration data from any grid node for the time period that you select. Data is collected and archived in a .tar.gz file that you can then download to your local computer.

Optionally, you can change the destination of audit logs and send audit information to an external syslog server. Local logs of audit records continue to be generated and stored when an external syslog server is configured. See link:../monitor/configure-audit-messages.html[Configure audit messages and external syslog server].

.Steps
. Select *SUPPORT* > *Tools* > *Logs*. A table of nodes displays.

. Select the grid nodes for which you want to collect log files.
+
You can sort by node name, site, and node type. The Site and Node type columns contain filters for selecting by  individual sites and node types.

. Select *Continue*.

. Select the date and time range of the data to be included in the log files.
+
If you select a very long time period or collect logs from all nodes in a large grid, the log archive could become too large to be stored on a node, or too large to be collected to the primary Admin Node for download. If either scenario occurs, restart log collection with a smaller set of data.

. Select the types of logs you want to collect.
+
* *Application logs*: Application-specific logs that technical support uses most frequently for troubleshooting. The logs collected are a subset of the available application logs.
* *Audit logs*: Logs containing the audit messages generated during normal system operation.
* *Network trace*: Logs used for network debugging.
* *Prometheus database*: Time series metrics from the services on all nodes.
+
. Optionally, enter notes about the log files you are gathering in the *Notes* text box.
+
You can use these notes to give technical support information about the problem that prompted you to collect the log files. Your notes are added to a file called `info.txt`, along with other information about the log file collection. The `info.txt` file is saved in the log file archive package.

. Enter the provisioning passphrase for your StorageGRID system in the *Provisioning passphrase* text box.
. Select *Collect logs*.
+
You can use the Logs page to monitor the progress of log file collection for each grid node.
+
If you receive an error message about log size, try collecting logs for a shorter time period or for fewer nodes.

. When log file collection is complete:
** Select *Download* to download the _.tar.gz_ file.
** Select *Send to AutoSupport* to send the _.tar.gz_ file to technical support.
+
The _.tar.gz_ file contains all log files from all grid nodes where log collection was successful. Inside the combined _.tar.gz_ file, there is one log file archive for each grid node.

. Select *Finish*.
+
CAUTION: The _.tar.gz_ file is deleted when you select *Finish*. Make sure you download or send the file first.