---
permalink: monitor/configure-email-notifications.html
sidebar: sidebar
keywords: notifications, email, system events, technical support
summary: 'As a StorageGRID administrator, you can configure an email server to send notifications that inform you, other administrators, and technical support about system events and issues.'
---
= Configure email notifications
:icons: font
:imagesdir: ../media/

[.lead]
As a StorageGRID administrator, you can configure an email server to send notifications that inform you, other administrators, and technical support about system events and issues.

.Before you begin

* You have link:../admin/admin-group-permissions.html[specific access permissions].
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].

.Steps

. Select *Configuration* > *Monitoring* > *Email server*.
+
The Email server page appears.

. Select the pull-down, *View features that might require an email server*.

. Select *View* for the feature you want to configure an email server for.
+
You are taken to the email configuration page for that feature.
+
* link:../monitor/email-alert-notifications.html[Set up email notifications for alerts]
+
For alerts, you can also link:../monitor/snmp-alert-notifications.html[set up SNMP notifications].

* Multi-admin verification (MAV)

* link:../monitor/configure-autosupport-grid-manager.html[Configure AutoSupport for Grid Manager]
+
You can send AutoSupport packages by email, HTTP, or HTTPS (recommended). 

