---
permalink: monitor/manage-io-prioritization.html
sidebar: sidebar
keywords: ec repair priority, ec purge priority
summary: 'Input/output (I/O) prioritization allows you to change the relative priorities for I/O operations on the grid.'
---
= Change I/O prioritization
:icons: font
:imagesdir: ../media/

[.lead]
Input/output (I/O) prioritization allows you to change the relative priorities for I/O operations on the grid. 

By default, client PUT and GET I/O traffic is given the highest priority over background activities such as purging erasure-coded (EC) data or EC repair. By lowering the priority of this I/O traffic, other tasks can possibly complete faster. The effectiveness of I/O prioritization changes is impacted by the rate of client requests, network traffic fluctuations, and other ongoing network tasks. 

.Before you begin

* Review the I/O prioritization page, to determine which options might impact your grid.
* Assess whether the ongoing client traffic can safely handle longer wait times or client timeouts.
* Be prepared to monitor the effect of the prioritization change and adjust as necessary. These changes might need hours to take effect.

.Steps

. Select *SUPPORT* > *I/O prioritization*.
. (Optional) Change priorities from the default values. For example:
+
* EC repair priority:

** *Critical*: EC repairs complete as soon as possible
** *Background (Default)*: EC repairs complete without disrupting other grid operations
+
NOTE: Use the default Background repair priority for grids that have RAID-based nodes.

* EC purge priority for background operations that purge EC data:
+
** *High* 
** *Medium*
** *Low (Default)* 

. Select *Save*.
. Monitor the link:../monitor/commonly-used-prometheus-metrics.html#where-are-prometheus-metrics-used[metrics] to assess the effect of prioritization changes.
