---
permalink: maintain/convert-to-data-only-node.html
sidebar: sidebar
keywords: storagegrid, recover, stop services, power down host, power off host
summary: 'To increase performance, you can convert a non-ADC Storage Node to a data-only Storage Node.'
---
= Convert a Storage Node to a data-only node
:icons: font
:imagesdir: ../media/

[.lead]
To increase performance, you can convert a non-ADC Storage Node to a data-only Storage Node.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:admin-group-permissions.html[Maintenance or Root access permission].
* The Storage Node you want to convert doesn't contain the ADC service, or you have link:../maintain/move-adc-service.html[moved the ADC service] to another node.
* The Storage Node isn't a metadata-only node or a data-only node.

.About this task
Use this procedure to convert one or more Storage Nodes that don't contain the ADC service into data-only nodes.

In addition to converting the Storage Node, this procedure decommissions Cassandra from the node. All metadata will migrate to combined or metadata-only Storage Nodes.

.Steps
. Record the node IDs of the non-ADC Storage Nodes you want to convert.

. From the top of the Grid Manager, select the help icon and select *API documentation*.

. Select *Go to private API documentation*.

. Select the `POST /private/convert-to-data-only-node/start` operation. Refer to link:../admin/using-grid-management-api.html#issue-api-requests[Issue API requests] for more information.
+
Each node will reboot during the procedure.

. You can use `GET /private/convert-to-data-only-node` to monitor the procedure. If errors occur, select `POST /private/convert-to-data-only-node/retry` to retry the procedure.

. link:../maintain/downloading-recovery-package.html[Download a recovery package] after completing this procedure.