---
permalink: maintain/convert-to-data-only-node.html
sidebar: sidebar
keywords: storagegrid, convert node, data-only node
summary: 'To increase performance, you can convert slower non-ADC Storage Nodes to data-only Storage Nodes.'
---
= Convert a Storage Node to a data-only node
:icons: font
:imagesdir: ../media/

[.lead]
To increase performance, you can convert slower non-ADC Storage Nodes to data-only Storage Nodes.

include::../_include/data-only-storage-node.adoc[]

When converting data-only nodes, the grid must contain a minimum of three combined or metadata-only Storage Nodes per site.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:../admin/admin-group-permissions.html[Maintenance or Root access permission].
* The Storage Node you want to convert doesn't contain the ADC service, or you have link:../maintain/move-adc-service.html[moved the ADC service] to another node.
* The Storage Node isn't a metadata-only node or a data-only node.
* The Storage Node you want to convert doesn't contain the ADC service, or you have link:../maintain/move-adc-service.html[moved the ADC service] to another node.
* There is enough metadata space on other nodes at the site (or you've link:../expand/index.html[expanded your grid]) to accommodate the metadata that will migrate from the Storage Node you are converting.

.About this task
Use this procedure to convert one or more combined Storage Nodes that don't contain the ADC service into data-only nodes.

In addition to converting the Storage Node, this procedure decommissions Cassandra from the node. All metadata will migrate to combined or metadata-only Storage Nodes. Depending on the amount of metadata that needs to migrate, this procedure could take up to several days per node to complete.

TIP: Generally, you can convert up to 10 nodes at a time if the metadata usage per node is less than 1 TB. If the metadata usage per node is more than 1 TB, convert up to 5 nodes per procedure instead. 

.Steps
. Record the node IDs of the non-ADC Storage Nodes you want to convert.

. From the top of the Grid Manager, select the help icon and select *API documentation*.

. Select *Go to private API documentation*.

. Select the `POST /private/convert-to-data-only-node/start` operation. Refer to link:../admin/using-grid-management-api.html#issue-api-requests[Issue API requests] for more information.
+
Each node will reboot during the procedure.

. You can use `GET /private/convert-to-data-only-node` to monitor the procedure. If errors occur, select `POST /private/convert-to-data-only-node/retry` to retry the procedure.

. link:../maintain/downloading-recovery-package.html[Download a recovery package] after completing this procedure.