---
permalink: maintain/convert-to-data-only-node.html
sidebar: sidebar
keywords: storagegrid, recover, stop services, power down host, power off host
summary: 'To increase performance, you can convert slower non-ADC Storage Nodes to data-only Storage Nodes.'
---
= Convert a Storage Node to a data-only node
:icons: font
:imagesdir: ../media/

[.lead]
To increase performance, you can convert slower non-ADC Storage Nodes to data-only Storage Nodes.

If you have a grid mixed with older and newer platforms for the Storage Nodes, the newer platforms typically provide good data capacity and metadata performance. Slower platforms might slow down metadata performance, so removing the metadata from slower nodes can improve performance.

For example, if you have a grid with older SG5600 or SG5700 nodes mixed with newer platforms, you can convert the SG5600- and SG5700-based Storage Nodes to data-only nodes, so that you retain good data capacity without impacting metadata performance.

Additionally, you can get more metadata capacity by removing low-RAM nodes from Cassandra. Then the per-node metadata capacity limit increases. Refer to link:../admin/managing-object-metadata-storage.html[Manage object metadata storage].

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:admin-group-permissions.html[Maintenance or Root access permission].
* The Storage Node you want to convert doesn't contain the ADC service, or you have link:../maintain/move-adc-service.html[moved the ADC service] to another node.
* The Storage Node isn't a metadata-only node or a data-only node.
* There is enough metadata space on other nodes at the site to accommodate the metadata that will migrate from the Storage Node you are converting.

.About this task
Use this procedure to convert one or more combined or metadata-only Storage Nodes that don't contain the ADC service into data-only nodes. The Storage Nodes must be on the same site.

In addition to converting the Storage Node, this procedure decommissions Cassandra from the node. All metadata will migrate to combined or metadata-only Storage Nodes. Depending on the amount of metadata that needs to migrate to other nodes, this procedure could take a few days per node to complete.

.Steps
. Record the node IDs of the non-ADC Storage Nodes you want to convert.

. From the top of the Grid Manager, select the help icon and select *API documentation*.

. Select *Go to private API documentation*.

. Select the `POST /private/convert-to-data-only-node/start` operation. Refer to link:../admin/using-grid-management-api.html#issue-api-requests[Issue API requests] for more information.
+
Each node will reboot during the procedure.

. You can use `GET /private/convert-to-data-only-node` to monitor the procedure. If errors occur, select `POST /private/convert-to-data-only-node/retry` to retry the procedure.

. link:../maintain/downloading-recovery-package.html[Download a recovery package] after completing this procedure.