---
permalink: maintain/downloading-recovery-package.html
sidebar: sidebar
keywords: storagegrid, recovery package
summary: 'The recovery package file allows you to restore the StorageGRID system if a failure occurs.'
---
= Download recovery package
:icons: font
:imagesdir: ../media/

[.lead]
The recovery package file allows you to restore the StorageGRID system if a failure occurs.

.Before you begin

* From any Admin Node, you are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the provisioning passphrase.
* You have link:../admin/admin-group-permissions.html[specific access permissions].

Download the current recovery package file before making grid topology changes to the StorageGRID system or before upgrading software. Then, download a new copy of the recovery package after making grid topology changes or after upgrading software.

.Steps

. Select *MAINTENANCE* > *System* > *Recovery package*.
. Enter the provisioning passphrase, and select *Start download*.
+
The download starts immediately.

. When the download completes, open the `.zip` file and confirm that you can access the contents, including the `Passwords.txt` file.
. Copy the downloaded recovery package file (`.zip`) to two safe, secure, and separate locations.
+
CAUTION: The recovery package file must be secured because it contains encryption keys and passwords that can be used to obtain data from the StorageGRID system.
