---
permalink: maintain/move-adc-service.html
sidebar: sidebar
keywords: storagegrid, move adc, adc quorum
summary: 'You can move the ADC service to another Storage Node on the same site.'
---
= Move the ADC service in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
You can move the ADC service to another Storage Node on the same site.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[Maintenance or Root access permission].
* The source node contains the ADC service.
* The target node doesn't contain the ADC service.
* The target node is either a metadata-only or combined (metadata and object data) node.
* The source node and target node are on the same site.

.About this task
Use the Move ADC procedure to manually move the ADC service between Storage Nodes. For example, you might want to redistribute ADC services across nodes or move the ADC service to a higher-performance node.

This procedure moves the ADC, IDNT, ACCT, and RSM services from one Storage Node to another on the same site. The RSM, IDNT, and ACCT services are dependent on the ADC service, so they automatically move when the ADC service moves.

[NOTE]
====
* You don't need to manually move the ADC service before link:../maintain/convert-to-data-only-node.html[converting a Storage Node to a data-only node] or decommissioning a Storage Node. These procedures automatically move the ADC service when required. Refer to link:../maintain/understanding-adc-service-quorum.html[What is the ADC quorum?] for details about the requirements.

* StorageGRID moves the ADC service to the newest Storage Nodes that meet the requirements for hosting the service.
====

.Steps
. Record the node IDs of the source and target nodes.
+
In the Grid Management API, the source node ID is referred to as `sourceNodeId`. The target node ID is referred to as `targetNodeId`.

. From the top of the Grid Manager, select the help icon and select *API documentation*.

. Select *Go to private API documentation*.

. Select the `POST /private/move-adc/start` operation. Refer to link:../admin/using-grid-management-api.html#issue-api-requests[Issue API requests] for more information.
+
During the procedure, the two nodes will reboot in sequence. The source node reboots first, followed by the target node.

. You can use `GET /private/move-adc` to monitor the procedure. If errors occur, select `POST /private/move-adc/retry` to retry the procedure.

. link:../maintain/downloading-recovery-package.html[Download a recovery package] after completing this procedure.