---
permalink: maintain/move-adc-service.html
sidebar: sidebar
keywords: storagegrid, move adc, adc quorum
summary: 'You can move the ADC service to another Storage Node on the same site.'
---
= Move the ADC service
:icons: font
:imagesdir: ../media/

[.lead]
You can move the ADC service to another Storage Node on the same site.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:admin-group-permissions.html[Maintenance or Root access permission].
* The source node contains the ADC service.
* The target node doesn't contain the ADC service.
* The target node is either a metadata-only or combined (metadata and object data) node.
* The source node and target node are on the same site.

.About this task
Use the Move ADC procedure when you want to:

* Decommission a Storage Node that contains the ADC service
* Convert an ADC node to a data-only node
* Add a node to run ADC-related tasks

When you want to decommission a Storage Node or link:../maintain/convert-to-data-only-node.html[convert a Storage Node to a data-only node], first you might need to use the Move ADC procedure. You'll need to ensure that the link:../maintain/understanding-adc-service-quorum.html[ADC quorum is maintained].

This procedure moves the ADC, RSM, IDNT, ACCT, and RSM services from one Storage Node to another on the same site. The RSM and ACCT services are dependent on the ADC service, so they automatically move when the ADC service moves.

.Steps
. Record the node IDs of the source and target nodes.
+
In the Grid Management API, the source node ID is referred to as `sourceNodeId`. The target node ID is referred to as `targetNodeId`.

. From the top of the Grid Manager, select the help icon and select *API documentation*.

. Select *Go to private API documentation*.

. Select the `POST /private/move-adc/start` operation. Refer to link:../admin/using-grid-management-api.html#issue-api-requests[Issue API requests] for more information.
+
Each node will reboot during the procedure.

. You can use `GET /private/move-adc` to monitor the procedure. If errors occur, select `POST /private/move-adc/retry` to retry the procedure.

. link:../maintain/downloading-recovery-package.html[Download a recovery package] after completing this procedure.