---
permalink: maintain/preparing-sg-appliance-for-primary-admin-node-replacement.html
sidebar: sidebar
keywords: storagegrid, recover, primary admin node, SG1000, SG100, appliance, prepare, installation software, software version
summary: 'Before replacing a virtual primary Admin Node with an SG1000 or SG100 appliance, install the appliance hardware, configure the network, and verify that the appliance software version matches the grid.'
---
= Prepare the SG1000/SG100 appliance for node replacement
:icons: font
:imagesdir: ../media/

[.lead]
Before replacing a virtual primary Admin Node with an SG1000 or SG100 appliance, install the appliance hardware, configure the network, and verify that the appliance software version matches the grid.

.Before you begin

* You have reviewed the link:replace-virtual-primary-admin-node.html[overview and prerequisites] for this procedure.
* No grid maintenance procedure is currently in progress.

.About this task

If you plan to reuse the existing primary Admin Node IP addresses on the appliance, shut down the existing virtual node before assigning those IPs to the appliance to avoid network conflicts. In that case, complete steps 1 and 3 through 6 of this procedure first, then follow the steps in link:replacing-virtual-primary-admin-node-with-sg-appliance.html[Replace the virtual primary Admin Node with the SG1000/SG100 appliance] through shutting down the existing node, before returning to complete step 2 of this procedure.

.Steps

. Follow the appliance installation guide to install the SG1000/SG100 appliance hardware and configure its network settings.

. Verify the appliance system clock:
 .. Open an SSH connection to port 8022 on the appliance using the admin account.
 .. Switch to root: 
 .. Verify that the appliance clock is within a few minutes of the current UTC time.
 .. If the clock has drifted, set the correct date and time:
+
----
date -s DD Mon YYYY HH:MM:SS
----

. Confirm that the preloaded software version on the appliance matches the StorageGRID version running on the grid:
 .. If the versions do not match, remove the preloaded software package from the appliance.
 .. Download the correct StorageGRID Debian installation package from the NetApp Support Site and extract the archive.

. Upload the correct installation software to the appliance:
 .. Upload the  file.
 .. Upload the  verification file.

. On the StorageGRID Appliance Installer *Home* tab, configure the node identity:
 .. Set the *Node type* to *Primary Admin*.
 .. Enter the node name. The node name must be identical to the existing virtual primary Admin Node name.
+
IMPORTANT: Do not click *Start Installation* at this step. Installation is started in the next procedure.

.What's next?
link:replacing-virtual-primary-admin-node-with-sg-appliance.html[Replace the virtual primary Admin Node with the SG1000/SG100 appliance]

// 2026 MAY 21, SGRIDDOC-260