---
permalink: maintain/recovering-from-admin-node-failures.html
sidebar: sidebar
keywords: recover, admin node failure, workflow
summary: "The recovery process for an Admin Node depends on whether it is the primary Admin Node or a non-primary Admin Node."
---
= Primary or non-primary Admin Node recovery in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
The recovery process for an Admin Node depends on whether it is the primary Admin Node or a non-primary Admin Node.

The high-level steps for recovering a primary or non-primary Admin Node are the same, although the details of the steps differ.

Always follow the correct recovery procedure for the Admin Node you are recovering. The procedures look the same at a high level, but differ in the details.

.Choices

* link:recovering-from-primary-admin-node-failures.html[Recover the primary Admin Node using the same primary Admin Node]
* link:recovering-from-primary-admin-node-failures-using-npan.html[Recover from primary Admin Node failures using a non-primary Admin Node]
* link:recovering-from-non-primary-admin-node-failures.html[Recover from non-primary Admin Node failures]
// 2026-04-15, SGWS-34291

