---
permalink: maintain/reviewing-warnings-about-storage-volume-recovery.html
sidebar: sidebar
keywords: storagegrid, recover, volume warning
summary: 'Before recovering failed storage volumes for a Storage Node, you must review the following warnings.'
---
= Warnings for storage volume recovery
:icons: font
:imagesdir: ../media/

[.lead]
Before recovering failed storage volumes for a Storage Node, review the following warnings.

The storage volumes (or rangedbs) in a Storage Node are identified by a hexadecimal number, which is known as the volume ID. For example, 0000 is the first volume and 000F is the sixteenth volume. The first object store (volume 0) on each Storage Node uses up to 4 TB of space for object metadata and Cassandra database operations; any remaining space on that volume is used for object data. All other storage volumes are used exclusively for object data.

The Cassandra database might be rebuilt as part of the volume recovery procedure if:

* Volume 0 fails and is recovered.
* The system drive and one or more storage volumes fails and is recovered.

When Cassandra is rebuilt, the system uses information from other Storage Nodes. If Cassandra has been rebuilt recently, Cassandra data might not yet be consistent across the grid. If too many Storage Nodes are offline:

* Some Cassandra data might not be available.
* Data loss could occur.

CAUTION: If more than one Storage Node has failed (or is offline), contact technical support. Don't perform the following recovery procedure. Data loss could occur.

NOTE: If more than one Storage Node at a site has failed, a site recovery procedure might be required. See link:how-site-recovery-is-performed-by-technical-support.html[How technical support recovers a site].

CAUTION: If ILM rules are configured to store only one replicated copy and the copy exists on a storage volume that has failed, you will not be able to recover the object.

.Related information

link:warnings-and-considerations-for-grid-node-recovery.html[Warnings and considerations for grid node recovery]