---
permalink: maintain/reviewing-warnings-for-system-drive-recovery.html
sidebar: sidebar
keywords: storagegrid, recover, system drive warning, storage node
summary: 'Before recovering a failed system drive of a Storage Node, review the general warnings and considerations for grid node recovery and the following specific warnings.'
---
= Warnings for Storage Node system drive recovery
:icons: font
:imagesdir: ../media/

[.lead]
Before recovering a failed system drive of a Storage Node, review the general
link:warnings-and-considerations-for-grid-node-recovery.html[warnings and considerations for grid node recovery] and the following specific warnings.

Storage Nodes have a Cassandra database that includes object metadata. The Cassandra database might be rebuilt if:

* A storage volume fails and is recovered.
* The system drive and one or more storage volumes fails and is recovered.

When Cassandra is rebuilt, the system uses information from other Storage Nodes. If Cassandra has been rebuilt recently, Cassandra data might not yet be consistent across the grid. If too many Storage Nodes are offline:

* Some Cassandra data might not be available.
* Data loss could occur.

CAUTION: If more than one Storage Node has failed (or is offline), contact technical support. Don't perform the following recovery procedure. Data loss could occur. For more information, refer to link:how-site-recovery-is-performed-by-technical-support.html[How technical support recovers a site].

CAUTION: If this Storage Node is in read-only maintenance mode to allow for the retrieval of objects by another Storage Node with failed storage volumes, recover volumes on the Storage Node with failed storage volumes before recovering this failed Storage Node. See the instructions to link:recovering-from-storage-volume-failure-where-system-drive-is-intact.html[recover from storage volume failure where system drive is intact].

CAUTION: If ILM rules are configured to store only one replicated copy and the copy exists on a storage volume that has failed, you will not be able to recover the object.