---
permalink: maintain/selecting-start-recovery-to-configure-storage-node.html
sidebar: sidebar
keywords: storagegrid, recover, storage node
summary: 'After replacing a Storage Node, you must select Start Recovery in the Grid Manager to configure the new node as a replacement for the failed node.'
---
= Select Start Recovery to configure StorageGRID Storage Node
:icons: font
:imagesdir: ../media/

[.lead]
After replacing a Storage Node, you must select Start Recovery in the Grid Manager to configure the new node as a replacement for the failed node.

.Before you begin

* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have the link:../admin/admin-group-permissions.html[Maintenance or Root access permission].
* You have the provisioning passphrase.
* You have deployed and configured the replacement node.
* You have the start date of any repair jobs for erasure-coded data.

.About this task

If the Storage Node is installed as a container on a Linux host, you must perform this step only if one of these is true:

* You had to use the `--force` flag to import the node, or you issued `storagegrid node force-recovery _node-name_`
* You had to do a full node reinstall, or you needed to restore /var/local.

.Steps

. Log in to the primary Admin Node. If the primary Admin Node is unavailable, use a non-primary Admin Node, if one exists.
. From the Grid Manager, select *Maintenance* > *Tasks* > *Node recovery*.
. Select the grid node you want to recover in the Pending Nodes list.
+
Nodes appear in the list after they fail, but you can't select a node until it has been reinstalled and is ready for recovery.

. Enter the *Provisioning Passphrase*.
. Click *Start Recovery*.
. Monitor the progress of the recovery by selecting *Maintenance* > *Recovery* > *In Progress*.
+
* If the grid node reaches the "Waiting for manual steps" stage, you must link:../maintain/remounting-and-reformatting-storage-volumes-manual-steps.html[remount and reformat the storage volumes manually]. Upon completion of the manual steps, proceed to link:../maintain/restoring-object-data-to-storage-volume.html[restore object data to the volumes].

* If the grid node recovery has transitioned from *In Progress*  to *Recovered* without going through the “Waiting for manual steps” stage, no further action is required.
+
[NOTE]
====
At any point during the recovery, you can select *Reset* to start a new recovery. A dialog box appears, indicating that the node will be left in an indeterminate state if you reset the procedure.

If you want to retry the recovery after resetting the procedure, you must restore the appliance node to a pre-installed state, as follows:

* *VMware*: Delete the deployed virtual grid node. Then, when you are ready to restart the recovery, redeploy the node.
* *Linux*: Restart the node by running this command on the Linux host: `storagegrid node force-recovery _node-name_`
====
// 2026-05-05, SGWS-34291
