---
permalink: maintain/understanding-adc-service-quorum.html
sidebar: sidebar
keywords: storagegrid, recover, adc, adc quorum
summary: 'The ADC quorum ensures that a minimum number of Administrative Domain Controller \(ADC\) services remain available at each site. StorageGRID automatically moves the ADC service during decommission when needed.'
---
= What is the ADC quorum?
:icons: font
:imagesdir: ../media/

[.lead]
The ADC quorum ensures that a minimum number of Administrative Domain Controller (ADC) services remain available at each site. StorageGRID automatically moves the ADC service during decommission when needed.

The ADC service, which is found on some Storage Nodes, maintains grid topology information and provides configuration services to the grid. The StorageGRID system requires a quorum of ADC services to be available at each site and at all times.

You can't decommission a Storage Node if removing the node would cause the ADC quorum to no longer be met. To satisfy the ADC quorum during a decommissioning, a minimum of three Storage Nodes at each site must have the ADC service. If a site has more than three Storage Nodes with the ADC service, a simple majority of those nodes must remain available after the decommissioning: `((0.5 * _Storage Nodes with ADC_) + 1)`

CAUTION: Use caution when you decommission Storage Nodes in a grid containing software-based metadata-only nodes. If you decommission all nodes configured to store _both_ objects and metadata, the ability to store objects is removed from the grid. See link:../primer/what-storage-node-is.html#types-of-storage-nodes[Types of Storage Nodes] for more information about metadata-only Storage Nodes.

For example, suppose a site currently includes six Storage Nodes with ADC services and you want to decommission three Storage Nodes. Because of the ADC quorum requirement, you must complete two decommission procedures, as follows:

* In the first decommission procedure, you must ensure that four Storage Nodes with ADC services remain available: `((0.5 * 6) + 1)`. This means that you can only decommission two Storage Nodes initially.
* In the second decommission procedure, you can remove the third Storage Node because the ADC quorum now requires only three ADC services to remain available: `((0.5 * 4) + 1)`.

When you decommission a Storage Node that has the ADC service, StorageGRID automatically moves the ADC service to another Storage Node on the same site if the decommission would bring the site's ADC count below quorum. The automatic move requires that all the nodes in the grid are connected and that non-ADC Storage Nodes are available on the same site to receive the service. The decommission procedure maintains a minimum of three ADC Storage Nodes per site. For example, if you decommission four or six ADC nodes on a site, three ADC Storage Nodes will remain after the procedure, assuming available non-ADC nodes exist on the same site.

If the ADC service can't be automatically moved, you can link:move-adc-service.html[manually move the ADC service] to another Storage Node on the same site or link:../expand/index.html[add a new Storage Node in an expansion] and specify that it should have an ADC service. Then, you can decommission the existing Storage Node without affecting the quorum.