---
permalink: troubleshoot/investigating-potentially-lost-objects.html
sidebar: sidebar
keywords: lost objects, investigating, objects
summary: 'When the *Objects potentially lost* alert is triggered, you must investigate immediately. Collect information about the affected objects and contact technical support.'
---
= Investigate potentially lost objects
:icons: font
:imagesdir: ../media/

[.lead]
When the *Objects potentially lost* alert is triggered, you must investigate immediately. Collect information about the affected objects and contact technical support.

.Before you begin
* You must be signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[specific access permissions].
* You must have the `Passwords.txt` file.

.About this task
The *Objects potentially lost* alert indicates that, according to the available information in StorageGRID, there are no copies of an object in the grid. Data might have been permanently lost.

Investigate lost object alerts immediately. You might need to take action to prevent further data loss. In some cases, you might be able to restore a lost object if you take prompt action.

.Steps
. Select *NODES*.
. Select *_Storage Node_* > *Objects*.
. Review the number of Lost objects shown in the Object counts table.
+
This number indicates the total number of objects this grid node detects as missing from the entire StorageGRID system. The value is the sum of the Lost objects counters of the Data store component within the LDR and DDS services.

. From an Admin Node, link:../audit/accessing-audit-log-file.html[access the audit log] to determine the unique identifier (UUID) of the object that triggered the *Objects potentially lost* alert:
.. Log in to the grid node:
... Enter the following command: `ssh admin@grid_node_IP`
... Enter the password listed in the `Passwords.txt` file.
... Enter the following command to switch to root: `su -`
... Enter the password listed in the `Passwords.txt` file.
When you are logged in as root, the prompt changes from `$` to `#`.
.. Change to the directory where the audit logs are located.
+
--
include::../_include/location-auditlog-files.adoc[]
--
.. Use grep to extract the Object Lost (OLST) audit messages. Enter: `grep OLST audit_file_name`
.. Note the UUID value included in the message.
+
----
Admin: # grep OLST audit.log
2020-02-12T19:18:54.780426 [AUDT:[CBID(UI64):0x38186FE53E3C49A5][UUID(CSTR):"926026C4-00A4-449B-AC72-BCCA72DD1311"]
[PATH(CSTR):"source/cats"][NOID(UI32):12288733][VOLI(UI64):3222345986][RSLT(FC32):NONE][AVER(UI32):10]
[ATIM(UI64):1581535134780426][ATYP(FC32):OLST][ANID(UI32):12448208][AMID(FC32):ILMX][ATID(UI64):7729403978647354233]]
----

. Look up the metadata for the lost object by using the UUID:
.. Select *ILM* > *Object metadata lookup*.
.. Enter the UUID, and select *Look Up*.
.. Review the locations in the metadata, and take the appropriate action:
+
[cols="2a,4a" options="header"]
|===

| Metadata| Conclusion

| Object <object_identifier> not found
| If the object isn't found, the message "ERROR":"" is returned.

If the object isn't found, <<reset-lost-obj-count,reset the Objects potentially lost counter>> to clear the alert. The lack of an object indicates that the object was intentionally deleted.

| Locations > 0
| If there are locations listed in the output, the *Objects potentially lost* alert might be a false positive.

Confirm that the objects exist. Use the Node ID and filepath listed in the output to confirm that the object file is in the listed location.

If the objects exist, <<reset-lost-obj-count,reset the Objects potentially lost counter>> to clear the alert.

|Locations = 0
|If there are no locations listed in the output, the object is potentially missing. Contact technical support.

Technical support might ask you to determine if there is a storage recovery procedure in progress. See the information about link:../maintain/restoring-volume.html[restoring object data using Grid Manager] and link:../maintain/restoring-object-data-to-storage-volume.html[restoring object data to a storage volume].
|===

. [[reset-lost-obj-count]]After you address lost object issues, reset the Objects potentially lost counter to ensure alerts aren't false positives:
.. Select *NODES*.
.. Select *_Storage Node_* > *Tasks*.
.. In the Reset Objects potentially lost counter section, select *Reset*.

// 2025 MAR 10, SGRIDDOC-110
// 2024 OCT 8: SGRIDDOC-104
// 2024 SEP 11: SGRIDDOC-96
