---
permalink: ilm/viewing-cloud-storage-pool-details.html
sidebar: sidebar
keywords: view cloud storage pool
summary: 'You can view the details of a Cloud Storage Pool to determine where it's used and to see which nodes and storage grades are included.'
---
= View Cloud Storage Pool details
:icons: font
:imagesdir: ../media/

[.lead]
You can view the details of a Cloud Storage Pool to determine where it's used and to see which nodes and storage grades are included.

.Before you begin
* You are signed in to the Grid Manager using a link:../admin/web-browser-requirements.html[supported web browser].
* You have link:../admin/admin-group-permissions.html[specific access permissions].

.Steps
. Select *ILM* > *Storage pools* > *Cloud Storage Pools*.
+
The Cloud Storage Pools table includes the following information for each Cloud Storage Pool that includes Storage Nodes:
+
* *Name*: The unique display name of the pool.
* *URI*: The Uniform Resource Identifier of the Cloud Storage Pool.
* *Provider type*: Which cloud provider is used for this Cloud Storage Pool. 
* *Container*: The name of the bucket used for the Cloud Storage Pool.
* *ILM usage*: How the pool is currently being used. A Cloud Storage Pool might be unused or it might be used in one or more ILM rules, erasure-coding profiles, or both.
* *Last error*: The last error detected during a health check of this Cloud Storage Pool. 

. To view details for a specific Cloud Storage Pool, select its name.
+
The details page for the pool appears.

. View the *Nodes* tab to learn about the Storage Nodes included in the Cloud Storage Pool.
+
The table includes the following information for each node:

* Node name
* Site name
* Storage grade
* Storage usage: The percentage of the total usable space for object data that has been used for the Storage Node.
+
NOTE: The same Storage usage (%) value is also shown in the Storage Used - Object Data chart for each Storage Node (select *NODES* > *_Storage Node_* > *Storage*).

. Select the *ILM usage* tab to determine if the Cloud Storage Pool is currently being used in any ILM rules or erasure-coding profiles.

. Optionally, go to the *ILM rules page* to learn about and manage any rules that use the Cloud Storage Pool.
+
See the link:working-with-ilm-rules-and-ilm-policies.html[instructions for working with ILM rules].

//If you previously uploaded a server or client certificate, you can select *Certificate details* to review the certificate that is currently in use.
