---
permalink: release-notes/changes-to-grid-management-api.html
sidebar: sidebar
keywords: grid management api, api, api version, swagger, rest api, usageCacheDuration 
summary: 'StorageGRID 12.0 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported.'
---
= Changes to the Grid Management API in StorageGRID
:icons: font
:imagesdir: ../media/

[.lead]
StorageGRID 12.0 uses version 4 of the Grid Management API. Version 4 deprecates version 3; however, versions 1, 2, and 3 are still supported. 

NOTE: You can continue to use deprecated versions of the management API with StorageGRID 12.0; however, support for these versions of the API will be removed in a future release of StorageGRID. After upgrading to StorageGRID 12.0, you can deactivate the deprecated APIs by using the `PUT /grid/config/management` API.

To learn more, go to link:../admin/using-grid-management-api.html[Use the Grid Management API].

== New endpoints for changing the BMC password and LAN IP settings

The following endpoint has been added to allow you to link:../harden/hardening-guidelines-for-storagegrid-nodes.html#change-appliance-bmc-password[change an appliance BMC password].

`PUT /bmc-configuration/root-password`

The following endpoints have been added to allow you to link:../maintain/changing-nodes-network-configuration.html#change-appliance-node-bmc-lan-ip-settings[change or view the BMC LAN IP settings].

`PUT /grid/bmc/{node-id}/lan-ip-config`

`GET /grid/bmc/{node-id}/lan-ip-config`

// 2024-07-2, SWGS-31283
// 2024-07-11, SGWS-32010
// 2025-02-24, SWGS-34787
