---
permalink: install-nodes/configuring-docker-storage-volume.html
sidebar: sidebar
keywords: how to configure container engine storage volume, Docker, Podman
summary: 'Before installing the Docker or Podman container engine, you might need to format the storage volume and mount it.'
---
= Configure container engine storage volume (Linux)
:icons: font
:imagesdir: ../media/

[.lead]
Before installing the Docker or Podman container engine, you might need to format the storage volume and mount it.

NOTE: Support for Docker as the container engine for software-only deployments is deprecated. Docker will be replaced with another container engine in a future release.

include::../_include/linux-distributions.adoc[]

.About this task

You can skip these steps if you plan to use the root volume for the Docker or Podman storage volume and have sufficient space available on the host partition containing:

* Podman: `/var/lib/containers`
* Docker: `/var/lib/docker`

.Steps

. Create a file system on the container engine storage volume:
+
[role="tabbed-block"]
====

.RHEL
--
----
sudo mkfs.ext4 container-engine-storage-volume-device
----
--

.Ubuntu or Debian
--
----
sudo mkfs.ext4 docker-storage-volume-device
----
--
====

. Mount the container engine storage volume:
+
[role="tabbed-block"]
====

.RHEL
--
* For Docker: 
+
----
sudo mkdir -p /var/lib/docker
sudo mount container-storage-volume-device /var/lib/docker
----
* For Podman: 
+
----
sudo mkdir -p /var/lib/containers
sudo mount container-storage-volume-device /var/lib/containers
----
--

.Ubuntu or Debian
--
----
sudo mkdir -p /var/lib/docker
sudo mount docker-storage-volume-device /var/lib/docker
----
* For Podman: 
+
----
sudo mkdir -p /var/lib/podman
sudo mount container-storage-volume-device /var/lib/podman
----
--
====

. Add an entry for the container storage volume device to /etc/fstab.
+
* RHEL: container-storage-volume-device
* Ubuntu or Debian: docker-storage-volume-device
+
This step ensures that the storage volume will remount automatically after host reboots.

== Install Docker 

The StorageGRID system can run on Linux as a collection of containers. 

* Before you can install StorageGRID for Ubuntu or Debian, you must install Docker.
* If you have chosen to use the Docker container engine, follow these steps to install Docker. Otherwise, <<install-podman-rhel,install Podman>>.

NOTE: Support for Docker as the container engine for software-only deployments is deprecated. Docker will be replaced with another container engine in a future release.

.Steps

. Install Docker by following the instructions for your Linux distribution.
+
NOTE: If Docker is not included with your Linux distribution, you can download it from the Docker website.

. Ensure Docker has been enabled and started by running the following two commands:
+
----
sudo systemctl enable docker
----
+
----
sudo systemctl start docker
----

. Confirm you have installed the expected version of Docker by entering the following:
+
----
sudo docker version
----
+
The Client and Server versions must be 1.11.0 or later.

[[install-podman-rhel]]
== Install Podman

The StorageGRID system runs as a collection of containers. If you have chosen to use the Podman container engine, follow these steps to install Podman. Otherwise, <<Install Docker,install Docker>>.

.Steps

. Install Podman and Podman-Docker by following the instructions for your Linux distribution.

+
NOTE: You must also install the Podman-Docker package when you install Podman.

. Confirm you have installed the expected version of Podman and Podman-Docker by entering the following:
+
----
sudo docker version
----
NOTE: The Podman-Docker package allows you to use Docker commands.
+
The Client and Server versions must be 3.2.3 or later.
+
----
Version: 3.2.3
API Version: 3.2.3
Go Version: go1.15.7
Built: Tue Jul 27 03:29:39 2021
OS/Arch: linux/amd64
----

.Related information

link:configuring-host-storage.html[Configure host storage]
